"use client";

// Incidents queue + 6-tab detail flyout — ported from
// itbd-lab/simulators/sentinel/js/sentinel-incidents.js (renderList() /
// detailHtml() / tabBody()). Severity x status filter chips are local UI
// state (matching source's module-level `filter` object); row click opens a
// Flyout with Overview / Alerts / Entities / Investigation graph / Alert
// evidence / Comments sub-tabs (source's `currentTab` + `tab()`/`setTab()`).
//
// The Alerts tab has no separate alerts array in this data model (source's
// `SentinelData.state` doesn't carry one either) — it synthesizes
// `alertsCount` placeholder rows from the incident's own severity/rule/product
// exactly like source's alertsTab() loop. The Investigation graph tab is a
// real computed radial SVG layout (entities placed at angle = 2*PI*i/n around
// a central incident node), ported faithfully from source's graphTab(),
// including its node-color-by-entity-type map. The Alert evidence tab is 5
// static reference rows, identical for every incident, matching source's
// evidenceTab() (which hardcodes the same 5 rows regardless of `inc`).

import { useMemo, useState } from "react";
import { toast } from "sonner";

import type { SentinelEntity, SentinelIncident, SentinelIncidentStatus, SentinelSeverity, SentinelState } from "@/lib/labs/simulators/sentinel/types";
import type { SentinelAction } from "@/lib/labs/simulators/sentinel/reducer";
import { DataTable, type DataTableColumn, EmptyState, Flyout, NativeSelect, SeverityBadge, StatusPill, SubTabBar, statusTone } from "./sentinel-ui";
import styles from "./sentinel-console.module.css";

const CURRENT_USER = "admin@itbd.onmicrosoft.com";

const SEVERITY_FILTERS: (SentinelSeverity | "all")[] = ["all", "High", "Medium", "Low", "Informational"];
const STATUS_FILTERS: (SentinelIncidentStatus | "all")[] = ["all", "New", "Active", "Closed"];

const DETAIL_TABS = [
  { key: "overview", label: "Overview" },
  { key: "alerts", label: "Alerts" },
  { key: "entities", label: "Entities" },
  { key: "graph", label: "Investigation graph" },
  { key: "evidence", label: "Alert evidence" },
  { key: "comments", label: "Comments" },
] as const;

type DetailTabKey = (typeof DETAIL_TABS)[number]["key"];

// Ported from SentinelPortal.ago() (source's relative-time helper) — no
// shared equivalent exists in this port yet, so it's defined locally.
function ago(iso: string): string {
  const t = Date.parse(iso);
  if (Number.isNaN(t)) return iso;
  const diffMs = Date.now() - t;
  const minutes = Math.floor(diffMs / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo ago`;
  return `${Math.floor(months / 12)}y ago`;
}

// ===================== Overview tab =====================

function OverviewTab({ incident }: { incident: SentinelIncident }) {
  const topEntities = incident.entities.slice(0, 5);
  return (
    <div className={styles.row}>
      <div>
        <div className={styles.card}>
          <div className={styles.cardTitle}>Description</div>
          <div style={{ fontSize: 13, lineHeight: 1.6, color: "#424242" }}>
            {incident.title}. Generated by analytics rule: <strong>{incident.rule}</strong>. Spans {incident.tactics.join(", ") || "no"} tactics and involves {incident.entitiesCount} entities.
          </div>
        </div>
        <div className={styles.card}>
          <div className={styles.cardTitle}>MITRE ATT&amp;CK</div>
          <div>
            <strong style={{ fontSize: 12 }}>Tactics:</strong>{" "}
            {incident.tactics.length ? incident.tactics.map((t) => <span key={t} className={styles.mitre}>{t}</span>) : <span style={{ fontSize: 12, color: "#605e5c" }}>None</span>}
          </div>
          <div style={{ marginTop: 6 }}>
            <strong style={{ fontSize: 12 }}>Techniques:</strong>{" "}
            {incident.techniques.length ? incident.techniques.map((t) => <span key={t} className={styles.mitre}>{t}</span>) : <span style={{ fontSize: 12, color: "#605e5c" }}>None</span>}
          </div>
        </div>
      </div>
      <div style={{ maxWidth: 300 }}>
        <div className={styles.card}>
          <div className={styles.cardTitle}>Top entities</div>
          {topEntities.length === 0 ? (
            <div style={{ fontSize: 12, color: "#605e5c" }}>No entities.</div>
          ) : (
            topEntities.map((e, i) => (
              <div key={`${e.name}-${i}`} className={styles.entityRow}>
                <span className={styles.entType}>{e.type}</span>
                <span className={styles.entName}>{e.name}</span>
              </div>
            ))
          )}
        </div>
        <div className={styles.card}>
          <div className={styles.cardTitle}>Product names</div>
          <div style={{ fontSize: 12 }}>
            {incident.productNames.length ? incident.productNames.map((p) => <div key={p}>{p}</div>) : <div style={{ color: "#605e5c" }}>None reported.</div>}
          </div>
        </div>
      </div>
    </div>
  );
}

// ===================== Alerts tab =====================
// No separate alerts array exists in this data model — synthesized purely
// from alertsCount, referencing the incident's own severity/rule/product,
// exactly matching source's alertsTab() loop (`inc.rule + ' #' + (i+1)`,
// `inc.productNames[0]`, `inc.tactics[0]`, `ago(inc.created)` repeated per row).

type SyntheticAlertRow = { index: number };

function AlertsTab({ incident }: { incident: SentinelIncident }) {
  const rows: SyntheticAlertRow[] = useMemo(() => Array.from({ length: incident.alertsCount }, (_, i) => ({ index: i })), [incident.alertsCount]);

  const columns: DataTableColumn<SyntheticAlertRow>[] = [
    { key: "severity", header: "Severity", render: () => <SeverityBadge severity={incident.severity} /> },
    { key: "alert", header: "Alert", render: (r) => `${incident.rule} #${r.index + 1}` },
    { key: "product", header: "Product", render: () => incident.productNames[0] ?? "" },
    { key: "tactic", header: "Tactic", render: () => incident.tactics[0] ?? "-" },
    { key: "time", header: "Time", render: () => ago(incident.created) },
  ];

  return <DataTable columns={columns} rows={rows} getRowKey={(r) => String(r.index)} emptyMessage="No alerts on this incident." />;
}

// ===================== Entities tab =====================

function EntitiesTab({ incident }: { incident: SentinelIncident }) {
  const columns: DataTableColumn<SentinelEntity>[] = [
    { key: "type", header: "Type", render: (e) => <span className={styles.pill}>{e.type}</span> },
    { key: "name", header: "Name", render: (e) => <span style={{ fontFamily: "Consolas, monospace" }}>{e.name}</span> },
    { key: "alerts", header: "Alerts (30d)", render: () => "3 alerts" },
    {
      key: "actions",
      header: "Actions",
      render: () => (
        <button type="button" className={styles.btnOutline} style={{ padding: "3px 8px", fontSize: 11 }} onClick={(e) => e.stopPropagation()}>
          Investigate
        </button>
      ),
    },
  ];

  return (
    <DataTable
      columns={columns}
      rows={incident.entities}
      getRowKey={(e) => `${e.type}-${e.name}-${incident.entities.indexOf(e)}`}
      emptyMessage="No entities on this incident."
    />
  );
}

// ===================== Investigation graph tab =====================
// Real computed radial SVG layout, ported faithfully from source's
// graphTab(): entities placed at angle = 2*PI*i/n around a central incident
// node at a fixed radius, connected to the center by dashed lines, color-coded
// by entity type. Colors are ported 1:1 from source's `nodeColors` map.

const GRAPH_WIDTH = 1000;
const GRAPH_HEIGHT = 420;
const GRAPH_RADIUS = 150;

const NODE_COLORS: Record<string, string> = {
  User: "#5b9bd5",
  Host: "#f9a825",
  IP: "#cf2030",
  URL: "#9c27b0",
  File: "#107c10",
  Process: "#d97900",
  "Azure resource": "#607d8b",
};
const DEFAULT_NODE_COLOR = "#607d8b";
const INCIDENT_NODE_COLOR = "#cf2030";

function GraphTab({ incident }: { incident: SentinelIncident }) {
  const cx = GRAPH_WIDTH / 2;
  const cy = GRAPH_HEIGHT / 2;
  const entities = incident.entities;

  const nodes = useMemo(
    () =>
      entities.map((e, i) => {
        const angle = (2 * Math.PI * i) / entities.length;
        return { x: cx + Math.cos(angle) * GRAPH_RADIUS, y: cy + Math.sin(angle) * GRAPH_RADIUS, entity: e };
      }),
    [entities, cx, cy],
  );

  return (
    <div>
      <div className={styles.graph}>
        <svg width="100%" height="100%" viewBox={`0 0 ${GRAPH_WIDTH} ${GRAPH_HEIGHT}`} preserveAspectRatio="xMidYMid meet">
          {nodes.map((n, i) => (
            <line key={`line-${i}`} x1={cx} y1={cy} x2={n.x} y2={n.y} stroke="#3a6ea5" strokeWidth={1.5} strokeDasharray="4 3" opacity={0.6} />
          ))}
          <g transform={`translate(${cx},${cy})`}>
            <circle r={34} fill={INCIDENT_NODE_COLOR} stroke="#fff" strokeWidth={3} />
            <text y={4} textAnchor="middle" fill="#fff" fontSize={12} fontWeight={600}>
              INCIDENT
            </text>
            <text y={60} textAnchor="middle" fill="#fff" fontSize={11}>
              {incident.id}
            </text>
          </g>
          {nodes.map((n, i) => {
            const color = NODE_COLORS[n.entity.type] ?? DEFAULT_NODE_COLOR;
            return (
              <g key={`node-${i}`} transform={`translate(${n.x},${n.y})`}>
                <circle r={22} fill={color} stroke="#fff" strokeWidth={2} />
                <text y={5} textAnchor="middle" fill="#fff" fontSize={11} fontWeight={600}>
                  {n.entity.type.substring(0, 1)}
                </text>
                <text y={40} textAnchor="middle" fill="#fff" fontSize={11}>
                  {n.entity.name}
                </text>
              </g>
            );
          })}
        </svg>
      </div>
      <div className={styles.legend}>
        {Object.entries(NODE_COLORS).map(([type, color]) => (
          <span key={type} className={styles.legendItem}>
            <span className={styles.legendDot} style={{ background: color }} />
            {type}
          </span>
        ))}
      </div>
      <div style={{ fontSize: 12, color: "#605e5c", marginTop: 8 }}>
        Investigation graph - showing entity relationships extracted from the incident&apos;s alerts. Click nodes in the real portal to drill into entity timelines.
      </div>
    </div>
  );
}

// ===================== Alert evidence tab =====================
// 5 static reference rows, identical for every incident — matching source's
// evidenceTab(), which hardcodes the same content regardless of `inc`.

const EVIDENCE_ROWS: { type: string; evidence: string; verdict: string; tone: "err" | "warn" }[] = [
  { type: "File", evidence: "invoice_q4.docm", verdict: "Malicious", tone: "err" },
  { type: "Hash", evidence: "a1b2c3d4e5f6...", verdict: "Malicious", tone: "err" },
  { type: "IP", evidence: "198.51.100.34", verdict: "Malicious", tone: "err" },
  { type: "URL", evidence: "https://hr-update[.]online/login", verdict: "Phish", tone: "err" },
  { type: "Process", evidence: "powershell.exe -enc ...", verdict: "Suspicious", tone: "warn" },
];

function EvidenceTab() {
  const columns: DataTableColumn<(typeof EVIDENCE_ROWS)[number]>[] = [
    { key: "type", header: "Type", render: (r) => r.type },
    { key: "evidence", header: "Evidence", render: (r) => <span style={{ fontFamily: "Consolas, monospace" }}>{r.evidence}</span> },
    { key: "verdict", header: "Verdict", render: (r) => <StatusPill tone={r.tone}>{r.verdict}</StatusPill> },
  ];
  return (
    <div className={styles.card}>
      <div className={styles.cardTitle}>Alert evidence</div>
      <DataTable columns={columns} rows={EVIDENCE_ROWS} getRowKey={(r) => r.evidence} />
    </div>
  );
}

// ===================== Comments tab =====================

function CommentsTab({ incident, dispatch }: { incident: SentinelIncident; dispatch: React.Dispatch<SentinelAction> }) {
  const [draft, setDraft] = useState("");

  function post() {
    const text = draft.trim();
    if (!text) return;
    dispatch({ type: "ADD_INCIDENT_COMMENT", id: incident.id, author: CURRENT_USER, text });
    toast.success("Comment added");
    setDraft("");
  }

  return (
    <div>
      {incident.comments.map((c) => (
        <div key={c.id} className={styles.card} style={{ marginBottom: 6 }}>
          <div style={{ fontSize: 11, color: "#605e5c" }}>
            {c.author} &middot; {new Date(c.time).toLocaleString()}
          </div>
          <div style={{ fontSize: 13, marginTop: 4 }}>{c.text}</div>
        </div>
      ))}
      <div className={styles.card}>
        <div className={styles.cardTitle}>Add comment</div>
        <textarea
          className={styles.textarea}
          rows={3}
          placeholder="Investigation notes, links to playbooks, etc."
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
        />
        <div style={{ marginTop: 8 }}>
          <button type="button" className={styles.btn} onClick={post}>
            Post comment
          </button>
        </div>
      </div>
    </div>
  );
}

// ===================== Detail flyout =====================

function IncidentDetailFlyout({ incident, dispatch, onClose }: { incident: SentinelIncident; dispatch: React.Dispatch<SentinelAction>; onClose: () => void }) {
  const [tab, setTab] = useState<DetailTabKey>("overview");
  const [ownerDraft, setOwnerDraft] = useState(incident.owner);

  function setStatus(status: SentinelIncidentStatus) {
    dispatch({ type: "UPDATE_INCIDENT", id: incident.id, patch: { status } });
    toast.success(`Incident ${incident.id} set to ${status}`);
    if (status === "Closed") onClose();
  }

  function assignToMe() {
    dispatch({ type: "UPDATE_INCIDENT", id: incident.id, patch: { owner: CURRENT_USER } });
    setOwnerDraft(CURRENT_USER);
    toast.success("Incident assigned to you");
  }

  function saveOwner() {
    const owner = ownerDraft.trim();
    if (!owner || owner === incident.owner) return;
    dispatch({ type: "UPDATE_INCIDENT", id: incident.id, patch: { owner } });
    toast.success(`Owner updated to ${owner}`);
  }

  const tabsWithCounts = DETAIL_TABS.map((t) => ({
    key: t.key,
    label: t.key === "alerts" ? `${t.label} (${incident.alertsCount})` : t.key === "entities" ? `${t.label} (${incident.entitiesCount})` : t.label,
  }));

  return (
    <Flyout
      title={incident.title}
      subtitle={incident.id}
      onClose={onClose}
      tabs={<SubTabBar tabs={tabsWithCounts} active={tab} onChange={(k) => setTab(k as DetailTabKey)} />}
      footer={
        <>
          <div style={{ flex: 1, display: "flex", alignItems: "center", gap: 8 }}>
            <input
              className={styles.input}
              style={{ width: 220 }}
              value={ownerDraft}
              onChange={(e) => setOwnerDraft(e.target.value)}
              placeholder="Owner email"
            />
            <button type="button" className={styles.btnOutline} onClick={saveOwner}>
              Save owner
            </button>
          </div>
          <NativeSelect
            value={incident.status}
            onChange={(v) => setStatus(v as SentinelIncidentStatus)}
            options={[
              { value: "New", label: "New" },
              { value: "Active", label: "Active" },
              { value: "Closed", label: "Closed" },
            ]}
          />
          <button type="button" className={styles.btnOutline} onClick={assignToMe}>
            Assign to me
          </button>
          <button type="button" className={styles.btn} onClick={() => setStatus("Closed")}>
            Close incident
          </button>
        </>
      }
    >
      <div style={{ display: "flex", flexWrap: "wrap", gap: 18, fontSize: 12, marginBottom: 14, paddingBottom: 14, borderBottom: "1px solid #e1dfdd" }}>
        <div>
          <div style={{ color: "#605e5c" }}>Severity</div>
          <SeverityBadge severity={incident.severity} />
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Status</div>
          <StatusPill tone={statusTone(incident.status)}>{incident.status}</StatusPill>
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Owner</div>
          <strong>{incident.owner}</strong>
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Alerts</div>
          <strong>{incident.alertsCount}</strong>
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Entities</div>
          <strong>{incident.entitiesCount}</strong>
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Created</div>
          <strong>{ago(incident.created)}</strong>
        </div>
        <div>
          <div style={{ color: "#605e5c" }}>Last modified</div>
          <strong>{ago(incident.lastModified)}</strong>
        </div>
      </div>

      {tab === "overview" && <OverviewTab incident={incident} />}
      {tab === "alerts" && <AlertsTab incident={incident} />}
      {tab === "entities" && <EntitiesTab incident={incident} />}
      {tab === "graph" && <GraphTab incident={incident} />}
      {tab === "evidence" && <EvidenceTab />}
      {tab === "comments" && <CommentsTab incident={incident} dispatch={dispatch} />}
    </Flyout>
  );
}

// ===================== List page =====================

type SeverityFilter = (typeof SEVERITY_FILTERS)[number];
type StatusFilter = (typeof STATUS_FILTERS)[number];

export function IncidentsPage({ state, dispatch }: { state: SentinelState; dispatch: React.Dispatch<SentinelAction> }) {
  const [severityFilter, setSeverityFilter] = useState<SeverityFilter>("all");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const filtered = useMemo(
    () =>
      state.incidents.filter((i) => {
        if (severityFilter !== "all" && i.severity !== severityFilter) return false;
        if (statusFilter !== "all" && i.status !== statusFilter) return false;
        return true;
      }),
    [state.incidents, severityFilter, statusFilter],
  );

  const selected = selectedId ? (state.incidents.find((i) => i.id === selectedId) ?? null) : null;

  const columns: DataTableColumn<SentinelIncident>[] = [
    { key: "severity", header: "Severity", render: (i) => <SeverityBadge severity={i.severity} /> },
    {
      key: "incident",
      header: "Incident",
      render: (i) => (
        <div>
          <div className={styles.rowLink}>{i.title}</div>
          <div style={{ fontSize: 11, color: "#605e5c" }}>{i.id}</div>
        </div>
      ),
    },
    { key: "alerts", header: "Alerts", render: (i) => i.alertsCount },
    { key: "entities", header: "Entities", render: (i) => i.entitiesCount },
    {
      key: "tactics",
      header: "Tactics",
      render: (i) => (
        <>
          {i.tactics.slice(0, 3).map((t) => (
            <span key={t} className={styles.mitre}>
              {t}
            </span>
          ))}
        </>
      ),
    },
    { key: "owner", header: "Owner", render: (i) => i.owner },
    { key: "status", header: "Status", render: (i) => <StatusPill tone={statusTone(i.status)}>{i.status}</StatusPill> },
    { key: "created", header: "Created", render: (i) => ago(i.created) },
    { key: "lastModified", header: "Last modified", render: (i) => ago(i.lastModified) },
  ];

  return (
    <div>
      <div className={styles.filterRow}>
        {SEVERITY_FILTERS.map((v) => (
          <button
            key={`sev-${v}`}
            type="button"
            className={`${styles.chip} ${severityFilter === v ? styles.chipActive : ""}`}
            onClick={() => setSeverityFilter(v)}
          >
            {v === "all" ? "Severity: any" : v}
          </button>
        ))}
        {STATUS_FILTERS.map((v) => (
          <button
            key={`status-${v}`}
            type="button"
            className={`${styles.chip} ${statusFilter === v ? styles.chipActive : ""}`}
            onClick={() => setStatusFilter(v)}
          >
            {v === "all" ? "Status: any" : v}
          </button>
        ))}
      </div>

      {filtered.length === 0 ? (
        <EmptyState message="No incidents match the current filter." />
      ) : (
        <DataTable columns={columns} rows={filtered} getRowKey={(i) => i.id} onRowClick={(i) => setSelectedId(i.id)} />
      )}

      {selected ? <IncidentDetailFlyout incident={selected} dispatch={dispatch} onClose={() => setSelectedId(null)} /> : null}
    </div>
  );
}
