/**
 * Production checklists seed data — extracted from the source itbd-lab
 * static site (production-checklists.html). Used by the one-time admin seed
 * endpoint to populate the labs production-checklists table; not read
 * directly at request time.
 *
 * The source nests checklist name -> category -> items[]. This flattens that
 * into one row per item, with `sortOrder` computed as the item's zero-based
 * position within its checklist + category (matching source array order).
 */

export type ProductionChecklistItemSeedEntry = {
  checklistName: string;
  category: string;
  item: string;
  sortOrder: number;
};

export const PRODUCTION_CHECKLIST_ITEMS_SEED: ProductionChecklistItemSeedEntry[] = [
  // ── Azure VM
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "VM size matches actual workload (right-sized using metrics from staging, not guessed).", "sortOrder": 0 },
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "Disk type matches IOPS needs (Standard SSD for dev / Premium SSD v2 for prod / Ultra Disk for SAP HANA).", "sortOrder": 1 },
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "OS disk + data disks have proper encryption (PMK or CMK).", "sortOrder": 2 },
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "Backup configured with Recovery Vault. Test restore was performed.", "sortOrder": 3 },
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "Hybrid Benefit applied if Windows / SQL licenses available.", "sortOrder": 4 },
  { "checklistName": "Azure VM", "category": "Compute + size", "item": "Auto-shutdown scheduled if non-prod.", "sortOrder": 5 },
  { "checklistName": "Azure VM", "category": "Network", "item": "No public IP unless absolutely required. Use Bastion or VPN.", "sortOrder": 0 },
  { "checklistName": "Azure VM", "category": "Network", "item": "NSG configured with least-privilege rules (no \"Any-Any\" allow).", "sortOrder": 1 },
  { "checklistName": "Azure VM", "category": "Network", "item": "NIC connected to correct subnet with proper routing.", "sortOrder": 2 },
  { "checklistName": "Azure VM", "category": "Network", "item": "Effective routes verified with Network Watcher.", "sortOrder": 3 },
  { "checklistName": "Azure VM", "category": "Network", "item": "If multi-zone: VM deployed across at least 2 AZs.", "sortOrder": 4 },
  { "checklistName": "Azure VM", "category": "Identity + Access", "item": "System or User-assigned Managed Identity assigned (not embedded credentials).", "sortOrder": 0 },
  { "checklistName": "Azure VM", "category": "Identity + Access", "item": "RBAC permissions granted to MI (least privilege).", "sortOrder": 1 },
  { "checklistName": "Azure VM", "category": "Identity + Access", "item": "No direct admin user account access; use PIM eligibility.", "sortOrder": 2 },
  { "checklistName": "Azure VM", "category": "Identity + Access", "item": "Anti-malware extension installed (Defender for Endpoint or Microsoft Antimalware).", "sortOrder": 3 },
  { "checklistName": "Azure VM", "category": "Monitoring", "item": "Diagnostic settings enabled → Log Analytics workspace.", "sortOrder": 0 },
  { "checklistName": "Azure VM", "category": "Monitoring", "item": "VM Insights agent installed for performance + dependency map.", "sortOrder": 1 },
  { "checklistName": "Azure VM", "category": "Monitoring", "item": "Alerts: CPU > 90% (5min), Memory > 90% (5min), Disk > 90% used.", "sortOrder": 2 },
  { "checklistName": "Azure VM", "category": "Monitoring", "item": "Action Group configured with on-call team.", "sortOrder": 3 },
  { "checklistName": "Azure VM", "category": "Monitoring", "item": "Defender for Servers enabled (Plan 1 or 2).", "sortOrder": 4 },
  { "checklistName": "Azure VM", "category": "Operations", "item": "Update Manager configured with maintenance window.", "sortOrder": 0 },
  { "checklistName": "Azure VM", "category": "Operations", "item": "Tags applied: Owner, Environment, CostCenter, ExpiryDate.", "sortOrder": 1 },
  { "checklistName": "Azure VM", "category": "Operations", "item": "Resource lock applied (CanNotDelete) to prevent accidental deletion.", "sortOrder": 2 },
  { "checklistName": "Azure VM", "category": "Operations", "item": "Runbook documented: how to scale up, restart, restore.", "sortOrder": 3 },

  // ── AKS Cluster
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Private cluster enabled (no public API endpoint).", "sortOrder": 0 },
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Cluster autoscaler enabled with min/max set.", "sortOrder": 1 },
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Multiple node pools: System (Linux), User (workloads), Spot (cheap batch).", "sortOrder": 2 },
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Node image upgrades scheduled (weekly).", "sortOrder": 3 },
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Kubernetes version pinned and tested before production.", "sortOrder": 4 },
  { "checklistName": "AKS Cluster", "category": "Cluster config", "item": "Surge max + max unavailable set for node pool upgrades (e.g. 33% surge, 0 unavailable).", "sortOrder": 5 },
  { "checklistName": "AKS Cluster", "category": "Network", "item": "Azure CNI Overlay or Cilium for pod networking.", "sortOrder": 0 },
  { "checklistName": "AKS Cluster", "category": "Network", "item": "NetworkPolicy enabled and default-deny applied per namespace.", "sortOrder": 1 },
  { "checklistName": "AKS Cluster", "category": "Network", "item": "API server in private subnet.", "sortOrder": 2 },
  { "checklistName": "AKS Cluster", "category": "Network", "item": "Outbound traffic via Azure Firewall or NAT Gateway (predictable egress IP).", "sortOrder": 3 },
  { "checklistName": "AKS Cluster", "category": "Network", "item": "Ingress controller (NGINX or App Gateway) with TLS via cert-manager.", "sortOrder": 4 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "Workload Identity Federation enabled (no service principal secrets in pods).", "sortOrder": 0 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "Azure RBAC for Kubernetes Authorization enabled.", "sortOrder": 1 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "Pod Security Standards \"Restricted\" enforced.", "sortOrder": 2 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "Container image scanning enabled (ACR + Defender for Containers).", "sortOrder": 3 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "No latest tag in deployment YAMLs.", "sortOrder": 4 },
  { "checklistName": "AKS Cluster", "category": "Identity + Security", "item": "Secrets stored in Key Vault, mounted via CSI driver (not in ConfigMaps).", "sortOrder": 5 },
  { "checklistName": "AKS Cluster", "category": "Observability", "item": "Container Insights + Managed Prometheus enabled.", "sortOrder": 0 },
  { "checklistName": "AKS Cluster", "category": "Observability", "item": "Grafana dashboard with workload-specific SLOs.", "sortOrder": 1 },
  { "checklistName": "AKS Cluster", "category": "Observability", "item": "Application Insights instrumentation in app pods.", "sortOrder": 2 },
  { "checklistName": "AKS Cluster", "category": "Observability", "item": "Log forwarding from pods to Log Analytics (FluentBit DaemonSet).", "sortOrder": 3 },
  { "checklistName": "AKS Cluster", "category": "Observability", "item": "Defender for Containers admission control + runtime protection on.", "sortOrder": 4 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "Pod replicas >= 3 for production workloads.", "sortOrder": 0 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "PodDisruptionBudget configured (minAvailable >= 2).", "sortOrder": 1 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "Liveness + Readiness probes defined for all containers.", "sortOrder": 2 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "Resource requests + limits set on every container.", "sortOrder": 3 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "HPA (Horizontal Pod Autoscaler) configured per workload.", "sortOrder": 4 },
  { "checklistName": "AKS Cluster", "category": "Resilience", "item": "Multi-zone node pools for AZ resilience.", "sortOrder": 5 },

  // ── App Service
  { "checklistName": "App Service", "category": "Plan + scaling", "item": "Plan tier: P1v3+ for production (S1 is dev/test only).", "sortOrder": 0 },
  { "checklistName": "App Service", "category": "Plan + scaling", "item": "Auto-scale rules: CPU > 70% → scale out; CPU < 30% → scale in; min 2 instances.", "sortOrder": 1 },
  { "checklistName": "App Service", "category": "Plan + scaling", "item": "Zone redundancy enabled (for Premium v3).", "sortOrder": 2 },
  { "checklistName": "App Service", "category": "Plan + scaling", "item": "Connection limit + worker count tuned per app load test.", "sortOrder": 3 },
  { "checklistName": "App Service", "category": "Network", "item": "VNet integration enabled (so backend can be private).", "sortOrder": 0 },
  { "checklistName": "App Service", "category": "Network", "item": "Access restrictions: only Front Door / specific IPs / Private Endpoint inbound.", "sortOrder": 1 },
  { "checklistName": "App Service", "category": "Network", "item": "Custom domain configured with managed SSL cert.", "sortOrder": 2 },
  { "checklistName": "App Service", "category": "Network", "item": "HTTPS only enforced + TLS 1.2 minimum.", "sortOrder": 3 },
  { "checklistName": "App Service", "category": "Identity + Security", "item": "Managed Identity assigned + permissions to Key Vault / SQL / Storage.", "sortOrder": 0 },
  { "checklistName": "App Service", "category": "Identity + Security", "item": "Easy Auth (App Service Authentication) or per-app OAuth/OIDC.", "sortOrder": 1 },
  { "checklistName": "App Service", "category": "Identity + Security", "item": "No secrets in App Settings; use Key Vault references.", "sortOrder": 2 },
  { "checklistName": "App Service", "category": "Identity + Security", "item": "Defender for App Service enabled.", "sortOrder": 3 },
  { "checklistName": "App Service", "category": "Slots + Deployment", "item": "Deployment slot used for staging → swap to production (zero-downtime).", "sortOrder": 0 },
  { "checklistName": "App Service", "category": "Slots + Deployment", "item": "Auto-swap or manual swap with smoke test gate.", "sortOrder": 1 },
  { "checklistName": "App Service", "category": "Slots + Deployment", "item": "Configuration that should NOT swap is marked as \"deployment slot setting\".", "sortOrder": 2 },
  { "checklistName": "App Service", "category": "Monitoring", "item": "Application Insights instrumentation deployed.", "sortOrder": 0 },
  { "checklistName": "App Service", "category": "Monitoring", "item": "Alerts: HTTP 5xx > 1% for 5min, response time > 2s, availability < 99%.", "sortOrder": 1 },
  { "checklistName": "App Service", "category": "Monitoring", "item": "Failed dependency tracking enabled.", "sortOrder": 2 },
  { "checklistName": "App Service", "category": "Monitoring", "item": "Live metrics + smart detection enabled.", "sortOrder": 3 },
  { "checklistName": "App Service", "category": "Monitoring", "item": "Slot-specific Application Insights for staging tests.", "sortOrder": 4 },

  // ── SQL Database
  { "checklistName": "SQL Database", "category": "Tier + sizing", "item": "Tier matches workload: General Purpose for OLTP / Business Critical for low-latency / Hyperscale for > 4 TB.", "sortOrder": 0 },
  { "checklistName": "SQL Database", "category": "Tier + sizing", "item": "vCore count right-sized using DTU usage stats from on-prem or non-prod.", "sortOrder": 1 },
  { "checklistName": "SQL Database", "category": "Tier + sizing", "item": "Backup storage redundancy set (Local / Zone / Geo).", "sortOrder": 2 },
  { "checklistName": "SQL Database", "category": "Tier + sizing", "item": "Point-in-time restore retention: 7-35 days based on RPO.", "sortOrder": 3 },
  { "checklistName": "SQL Database", "category": "Network", "item": "Public network access DISABLED.", "sortOrder": 0 },
  { "checklistName": "SQL Database", "category": "Network", "item": "Private Endpoint configured in target VNet.", "sortOrder": 1 },
  { "checklistName": "SQL Database", "category": "Network", "item": "Firewall rules for service-specific IPs only.", "sortOrder": 2 },
  { "checklistName": "SQL Database", "category": "Network", "item": "Azure services allowed: OFF (use Private Endpoint or explicit IPs).", "sortOrder": 3 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "Microsoft Entra authentication enabled + AD admin set.", "sortOrder": 0 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "SQL admin user disabled (use AAD admin instead).", "sortOrder": 1 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "TDE (Transparent Data Encryption) enabled with CMK in Key Vault.", "sortOrder": 2 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "Always Encrypted with secure enclaves for sensitive columns.", "sortOrder": 3 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "Audit log enabled + sent to Log Analytics.", "sortOrder": 4 },
  { "checklistName": "SQL Database", "category": "Identity + Security", "item": "Defender for SQL enabled (vulnerability assessment + advanced threat protection).", "sortOrder": 5 },
  { "checklistName": "SQL Database", "category": "High availability + DR", "item": "Zone-redundant tier enabled (Business Critical + GP).", "sortOrder": 0 },
  { "checklistName": "SQL Database", "category": "High availability + DR", "item": "Failover Group configured for cross-region DR.", "sortOrder": 1 },
  { "checklistName": "SQL Database", "category": "High availability + DR", "item": "Read replicas configured if read-heavy workload.", "sortOrder": 2 },
  { "checklistName": "SQL Database", "category": "High availability + DR", "item": "Long-term backup retention configured (7 years for compliance).", "sortOrder": 3 },
  { "checklistName": "SQL Database", "category": "High availability + DR", "item": "Geo-restore drill performed (quarterly).", "sortOrder": 4 },
  { "checklistName": "SQL Database", "category": "Performance + monitoring", "item": "Query Performance Insight enabled.", "sortOrder": 0 },
  { "checklistName": "SQL Database", "category": "Performance + monitoring", "item": "Auto-tuning configured (CREATE_INDEX, DROP_INDEX, FORCE_LAST_GOOD_PLAN).", "sortOrder": 1 },
  { "checklistName": "SQL Database", "category": "Performance + monitoring", "item": "Resource Health alerts configured.", "sortOrder": 2 },
  { "checklistName": "SQL Database", "category": "Performance + monitoring", "item": "Slow query alert: DTU > 80% for 10 min.", "sortOrder": 3 },
  { "checklistName": "SQL Database", "category": "Performance + monitoring", "item": "Connection limit alert.", "sortOrder": 4 },

  // ── Storage Account
  { "checklistName": "Storage Account", "category": "Access", "item": "Public network access DISABLED.", "sortOrder": 0 },
  { "checklistName": "Storage Account", "category": "Access", "item": "Private Endpoint configured.", "sortOrder": 1 },
  { "checklistName": "Storage Account", "category": "Access", "item": "Allow Azure trusted services if needed.", "sortOrder": 2 },
  { "checklistName": "Storage Account", "category": "Access", "item": "Account key access disabled (AAD-only).", "sortOrder": 3 },
  { "checklistName": "Storage Account", "category": "Access", "item": "Anonymous public access disabled at account level.", "sortOrder": 4 },
  { "checklistName": "Storage Account", "category": "Encryption", "item": "Encryption at rest: Customer-Managed Key (CMK) in Key Vault.", "sortOrder": 0 },
  { "checklistName": "Storage Account", "category": "Encryption", "item": "Secure transfer required: ON (HTTPS only).", "sortOrder": 1 },
  { "checklistName": "Storage Account", "category": "Encryption", "item": "Minimum TLS version: 1.2.", "sortOrder": 2 },
  { "checklistName": "Storage Account", "category": "Encryption", "item": "Infrastructure encryption: enabled if regulatory requirement.", "sortOrder": 3 },
  { "checklistName": "Storage Account", "category": "Data protection", "item": "Soft delete: enabled for blobs (7-90 days).", "sortOrder": 0 },
  { "checklistName": "Storage Account", "category": "Data protection", "item": "Soft delete: enabled for containers.", "sortOrder": 1 },
  { "checklistName": "Storage Account", "category": "Data protection", "item": "Versioning: enabled if needed.", "sortOrder": 2 },
  { "checklistName": "Storage Account", "category": "Data protection", "item": "Point-in-time restore: enabled.", "sortOrder": 3 },
  { "checklistName": "Storage Account", "category": "Data protection", "item": "Immutable storage / WORM: if regulatory.", "sortOrder": 4 },
  { "checklistName": "Storage Account", "category": "Lifecycle + cost", "item": "Lifecycle management rules: blob → Cool after 30d → Archive after 180d → Delete after 7y.", "sortOrder": 0 },
  { "checklistName": "Storage Account", "category": "Lifecycle + cost", "item": "Tags applied for cost allocation.", "sortOrder": 1 },
  { "checklistName": "Storage Account", "category": "Lifecycle + cost", "item": "Reserved capacity considered if > 100 TB.", "sortOrder": 2 },
  { "checklistName": "Storage Account", "category": "Lifecycle + cost", "item": "Inventory + analytics enabled.", "sortOrder": 3 },
  { "checklistName": "Storage Account", "category": "Monitoring", "item": "Diagnostic settings → Log Analytics.", "sortOrder": 0 },
  { "checklistName": "Storage Account", "category": "Monitoring", "item": "Alerts on availability < 99%, error rate > 1%, capacity > 80%.", "sortOrder": 1 },
  { "checklistName": "Storage Account", "category": "Monitoring", "item": "Defender for Storage enabled.", "sortOrder": 2 },

  // ── Function App
  { "checklistName": "Function App", "category": "Hosting", "item": "Plan: Consumption / Premium / Dedicated based on need (Premium for VNet integration, no cold start).", "sortOrder": 0 },
  { "checklistName": "Function App", "category": "Hosting", "item": "Runtime version pinned.", "sortOrder": 1 },
  { "checklistName": "Function App", "category": "Hosting", "item": "Always On enabled (for non-Consumption).", "sortOrder": 2 },
  { "checklistName": "Function App", "category": "Hosting", "item": "64-bit platform.", "sortOrder": 3 },
  { "checklistName": "Function App", "category": "Network", "item": "VNet integration for outbound (Premium / Dedicated).", "sortOrder": 0 },
  { "checklistName": "Function App", "category": "Network", "item": "Private Endpoint for inbound.", "sortOrder": 1 },
  { "checklistName": "Function App", "category": "Network", "item": "Access restrictions: only allowed networks/IPs.", "sortOrder": 2 },
  { "checklistName": "Function App", "category": "Network", "item": "CORS configured properly (no *).", "sortOrder": 3 },
  { "checklistName": "Function App", "category": "Identity + Security", "item": "Managed Identity assigned, no secrets in code.", "sortOrder": 0 },
  { "checklistName": "Function App", "category": "Identity + Security", "item": "Function-level authorization keys not used (use OAuth/Entra).", "sortOrder": 1 },
  { "checklistName": "Function App", "category": "Identity + Security", "item": "Defender for App Service enabled.", "sortOrder": 2 },
  { "checklistName": "Function App", "category": "Identity + Security", "item": "Function timeout configured (max 10 min Consumption, 60 min Premium).", "sortOrder": 3 },
  { "checklistName": "Function App", "category": "Observability", "item": "Application Insights connected.", "sortOrder": 0 },
  { "checklistName": "Function App", "category": "Observability", "item": "Sampling configured (5-10% for high-volume).", "sortOrder": 1 },
  { "checklistName": "Function App", "category": "Observability", "item": "Alerts: execution failures, dependency failures, throttling.", "sortOrder": 2 },
  { "checklistName": "Function App", "category": "Observability", "item": "Performance counter alerts.", "sortOrder": 3 },

  // ── Sentinel + SOC
  { "checklistName": "Sentinel + SOC", "category": "Workspace + tier", "item": "Dedicated Sentinel workspace (not shared with VM logs).", "sortOrder": 0 },
  { "checklistName": "Sentinel + SOC", "category": "Workspace + tier", "item": "Daily cap configured to prevent runaway costs.", "sortOrder": 1 },
  { "checklistName": "Sentinel + SOC", "category": "Workspace + tier", "item": "Retention: 90 days hot + archive tier for 1-2 years (or per compliance).", "sortOrder": 2 },
  { "checklistName": "Sentinel + SOC", "category": "Workspace + tier", "item": "Commitment tier purchased if > 100 GB/day.", "sortOrder": 3 },
  { "checklistName": "Sentinel + SOC", "category": "Data sources", "item": "M365 Defender connector enabled (FREE in Sentinel).", "sortOrder": 0 },
  { "checklistName": "Sentinel + SOC", "category": "Data sources", "item": "Azure Activity logs.", "sortOrder": 1 },
  { "checklistName": "Sentinel + SOC", "category": "Data sources", "item": "Entra ID Sign-in + Audit logs.", "sortOrder": 2 },
  { "checklistName": "Sentinel + SOC", "category": "Data sources", "item": "3rd-party: Firewall, CASB, Cloud Apps connectors.", "sortOrder": 3 },
  { "checklistName": "Sentinel + SOC", "category": "Data sources", "item": "Diagnostic settings on Key Vault, Storage, Application Insights → Sentinel.", "sortOrder": 4 },
  { "checklistName": "Sentinel + SOC", "category": "Analytics rules", "item": "Microsoft-shipped rules: enabled with severity tuning.", "sortOrder": 0 },
  { "checklistName": "Sentinel + SOC", "category": "Analytics rules", "item": "Custom rules: covering top 10 MITRE ATT&CK techniques relevant to your env.", "sortOrder": 1 },
  { "checklistName": "Sentinel + SOC", "category": "Analytics rules", "item": "Entity grouping configured to reduce noise.", "sortOrder": 2 },
  { "checklistName": "Sentinel + SOC", "category": "Analytics rules", "item": "Each rule has assignment + SLA + escalation path.", "sortOrder": 3 },
  { "checklistName": "Sentinel + SOC", "category": "Analytics rules", "item": "Schedule rules: review monthly for false positive rate.", "sortOrder": 4 },
  { "checklistName": "Sentinel + SOC", "category": "Automation + IR", "item": "Playbooks for top 5 incident types (disable user, isolate device, etc.).", "sortOrder": 0 },
  { "checklistName": "Sentinel + SOC", "category": "Automation + IR", "item": "Automation rules triggering playbooks on TruePositive.", "sortOrder": 1 },
  { "checklistName": "Sentinel + SOC", "category": "Automation + IR", "item": "On-call rotation defined.", "sortOrder": 2 },
  { "checklistName": "Sentinel + SOC", "category": "Automation + IR", "item": "Incident response runbooks documented.", "sortOrder": 3 },
  { "checklistName": "Sentinel + SOC", "category": "Automation + IR", "item": "Tabletop exercise: phishing IR drill (quarterly).", "sortOrder": 4 },
  { "checklistName": "Sentinel + SOC", "category": "Workbooks + reporting", "item": "MITRE ATT&CK workbook configured for coverage.", "sortOrder": 0 },
  { "checklistName": "Sentinel + SOC", "category": "Workbooks + reporting", "item": "Identity & Access workbook.", "sortOrder": 1 },
  { "checklistName": "Sentinel + SOC", "category": "Workbooks + reporting", "item": "Top 10 incidents weekly dashboard.", "sortOrder": 2 },
  { "checklistName": "Sentinel + SOC", "category": "Workbooks + reporting", "item": "Monthly Threat Intelligence report.", "sortOrder": 3 }
];
