/**
 * Services catalog seed data — extracted from the source itbd-lab static site
 * (services-catalog.html). Used by the one-time admin seed endpoint to populate
 * the labs services catalog table; not read directly at request time.
 */

export type ServicesCatalogSeedEntry = {
  cat: string;
  name: string;
  icon: string;
  desc: string;
  when: string;
  alt: string;
  price: string;
};

export const SERVICES_CATALOG_SEED: ServicesCatalogSeedEntry[] = [
  // ── Azure Compute
  { "cat": "Compute", "name": "Virtual Machines (VM)", "icon": "🖥️", "desc": "IaaS — full control over the OS and software. Spin up Windows / Linux servers in minutes.", "when": "Lift-and-shift apps, custom OS requirements, workloads needing specific drivers.", "alt": "AWS EC2 / GCP Compute Engine", "price": "mid" },
  { "cat": "Compute", "name": "Virtual Machine Scale Sets (VMSS)", "icon": "🖥️", "desc": "Identical VMs that scale out / in automatically. Up to 1000 VMs per scale set.", "when": "Stateless web tiers, batch compute, gaming, CI build pools.", "alt": "AWS Auto Scaling Groups / GCP Managed Instance Groups", "price": "mid" },
  { "cat": "Compute", "name": "Azure App Service", "icon": "🌐", "desc": "PaaS web hosting. Deploy code or container. Built-in auth, SSL, deployment slots, autoscaling.", "when": "Web apps, REST APIs, mobile backends. Easier than managing IIS or Kestrel.", "alt": "AWS Elastic Beanstalk / GCP App Engine", "price": "low" },
  { "cat": "Compute", "name": "Azure Functions", "icon": "⚡", "desc": "Serverless compute. Pay per execution. Triggers: HTTP, Timer, Queue, Event Grid, Blob, etc.", "when": "Event-driven workloads, scheduled jobs, glue code, webhooks, small APIs.", "alt": "AWS Lambda / GCP Cloud Functions", "price": "low" },
  { "cat": "Compute", "name": "Azure Container Apps", "icon": "📦", "desc": "Serverless containers. KEDA scaling, Dapr integration. Cheaper than AKS for small workloads.", "when": "Microservices, event-driven containers, gradual move from Functions to containers.", "alt": "AWS ECS Fargate / GCP Cloud Run", "price": "low" },
  { "cat": "Compute", "name": "Azure Kubernetes Service (AKS)", "icon": "☸️", "desc": "Managed Kubernetes. Microsoft manages the control plane; you manage workloads + node pools.", "when": "Microservices, polyglot apps, container-native teams, multi-region deployments.", "alt": "AWS EKS / GCP GKE", "price": "mid" },
  { "cat": "Compute", "name": "Azure Container Instances (ACI)", "icon": "📦", "desc": "Run a single container without orchestration overhead. Per-second billing.", "when": "CI build agents, batch tasks, simple stateless containers.", "alt": "AWS ECS on Fargate / GCP Cloud Run jobs", "price": "low" },
  { "cat": "Compute", "name": "Azure Batch", "icon": "🧪", "desc": "Large-scale parallel + HPC compute. Manages a pool of VMs.", "when": "Rendering farms, ML training fleets, financial risk modelling, scientific compute.", "alt": "AWS Batch / GCP Batch", "price": "high" },
  { "cat": "Compute", "name": "Azure Virtual Desktop (AVD)", "icon": "🖱️", "desc": "Cloud-hosted Windows desktops + apps via RDP. Multi-session Win 11.", "when": "Replacing thin clients, VDI for remote workers, app virtualization.", "alt": "Amazon WorkSpaces / GCP no native", "price": "mid" },
  { "cat": "Compute", "name": "Windows 365 (Cloud PC)", "icon": "💻", "desc": "Per-user Cloud PC. Fixed monthly per-user cost. Microsoft manages everything.", "when": "BYOD scenarios, frontline workers, simple \"I want a Windows desktop in the cloud\".", "alt": "AWS WorkSpaces / GCP no native", "price": "mid" },

  // ── Azure Storage
  { "cat": "Storage", "name": "Azure Blob Storage", "icon": "🗃️", "desc": "Object storage for unstructured data. Tiers: Hot / Cool / Cold / Archive. 99.99% SLA.", "when": "Backups, archives, web content, IoT telemetry, data lake foundation.", "alt": "AWS S3 / GCP Cloud Storage", "price": "low" },
  { "cat": "Storage", "name": "Azure Files", "icon": "📁", "desc": "Managed SMB / NFS shares. AD-integrated authentication.", "when": "Lift-and-shift file servers, FSLogix profiles, dev/test shared storage.", "alt": "AWS EFS / FSx | GCP Filestore", "price": "mid" },
  { "cat": "Storage", "name": "Azure Disk Storage (Managed Disks)", "icon": "💾", "desc": "Block storage attached to VMs. Tiers: Standard HDD, Standard SSD, Premium SSD, Premium SSD v2, Ultra Disk.", "when": "Boot disks, database storage, anything VM-attached. Premium v2 for IOPS-tunable.", "alt": "AWS EBS / GCP Persistent Disk", "price": "mid" },
  { "cat": "Storage", "name": "Azure Data Lake Storage Gen2", "icon": "🌊", "desc": "Blob storage with hierarchical namespace + ACLs. For analytics workloads.", "when": "Data lakes, big data analytics, Synapse / Databricks integration.", "alt": "AWS S3 + Lake Formation / GCP Cloud Storage", "price": "low" },
  { "cat": "Storage", "name": "Azure Backup", "icon": "🔄", "desc": "Centralized backup service. VM, SQL DB, Files, Azure Disk. Cross-region restore.", "when": "Any production resource. Always combine with snapshots for fast recovery.", "alt": "AWS Backup / GCP Backup and DR", "price": "low" },
  { "cat": "Storage", "name": "Azure Site Recovery (ASR)", "icon": "🔁", "desc": "DR replication for VMs. Replicates Azure → Azure, on-prem → Azure, Azure → on-prem.", "when": "DR strategy with RPO < 5 min and RTO < 1 hour.", "alt": "AWS DRS / GCP no native", "price": "mid" },
  { "cat": "Storage", "name": "Azure NetApp Files (ANF)", "icon": "💎", "desc": "Premium NFS / SMB storage. Sub-millisecond latency. SAP HANA certified.", "when": "High-performance NFS / SMB workloads. SAP HANA. AVD with extreme IOPS.", "alt": "AWS FSx for NetApp ONTAP / GCP Cloud Filestore Premium", "price": "high" },
  { "cat": "Storage", "name": "StorSimple (retired)", "icon": "🗄️", "desc": "Hybrid storage device with cloud tiering. Replaced by Azure File Sync.", "when": "<del>Don't use — retired</del>. Migrate to Azure File Sync.", "alt": "Migration tool", "price": "free" },

  // ── Azure Networking
  { "cat": "Networking", "name": "Virtual Network (VNet)", "icon": "🌐", "desc": "Azure private network. /8 to /29 address space. Subnets, peering, route tables.", "when": "Any resource needing private network isolation. Foundation of every Azure deployment.", "alt": "AWS VPC / GCP VPC", "price": "free" },
  { "cat": "Networking", "name": "Azure Firewall", "icon": "🛡️", "desc": "Managed L4-L7 firewall. Standard / Premium tier. Premium adds TLS inspection, URL filtering, IDPS.", "when": "Hub VNet egress filtering, central security policy, threat intel.", "alt": "AWS Network Firewall / GCP Cloud NGFW", "price": "mid" },
  { "cat": "Networking", "name": "Application Gateway", "icon": "🚪", "desc": "Regional L7 load balancer. WAF (OWASP CRS), path-based routing, SSL termination.", "when": "Internal-facing web apps, multi-tenant ingress, AKS Application Routing add-on.", "alt": "AWS Application Load Balancer / GCP Load Balancing", "price": "mid" },
  { "cat": "Networking", "name": "Azure Load Balancer", "icon": "⚖️", "desc": "Regional L4 TCP/UDP load balancer. Standard SKU is zone-redundant.", "when": "Backing for VMSS, AKS internal LB, simple TCP services.", "alt": "AWS Network Load Balancer / GCP TCP/UDP LB", "price": "low" },
  { "cat": "Networking", "name": "Azure Front Door", "icon": "🌍", "desc": "Global L7 load balancer + CDN + WAF + DDoS. Anycast edge with 192 PoPs.", "when": "Global multi-region apps, CDN, WAF Premium with Microsoft TI.", "alt": "AWS CloudFront + ALB / GCP Cloud CDN", "price": "mid" },
  { "cat": "Networking", "name": "Traffic Manager", "icon": "🚦", "desc": "DNS-based global traffic routing. Geo-routing, priority, weighted, performance.", "when": "When you need DNS-only routing (no payload inspection). Slower failover than Front Door.", "alt": "AWS Route 53 / GCP Cloud DNS", "price": "low" },
  { "cat": "Networking", "name": "ExpressRoute", "icon": "🔗", "desc": "Private fiber from on-prem to Azure. 50 Mbps to 100 Gbps. Bypasses internet.", "when": "Enterprise hybrid connectivity. Latency-sensitive workloads. Compliance.", "alt": "AWS Direct Connect / GCP Interconnect", "price": "high" },
  { "cat": "Networking", "name": "VPN Gateway", "icon": "🔐", "desc": "Site-to-site IPsec VPN or point-to-site for individuals.", "when": "On-prem connectivity without ExpressRoute. Branch offices.", "alt": "AWS VPN / GCP Cloud VPN", "price": "low" },
  { "cat": "Networking", "name": "Virtual WAN", "icon": "🕸️", "desc": "Managed SD-WAN service. Hub-and-spoke as a service.", "when": "Multi-region (6+) deployments, branch SD-WAN, scale beyond hub-spoke limits.", "alt": "AWS Cloud WAN / GCP Network Connectivity Center", "price": "mid" },
  { "cat": "Networking", "name": "Azure Bastion", "icon": "🏰", "desc": "RDP / SSH access to VMs without public IPs. Browser or native client.", "when": "Secure admin access. Replace public RDP / SSH. Premium adds session recording.", "alt": "AWS Systems Manager Session Manager / GCP IAP for SSH", "price": "mid" },
  { "cat": "Networking", "name": "Private Link / Private Endpoint", "icon": "🔒", "desc": "Private IP in your VNet for PaaS services (Storage, SQL, Cosmos, App Service, etc.).", "when": "Production any PaaS. Removes public exposure. Compliance.", "alt": "AWS PrivateLink / GCP Private Service Connect", "price": "low" },
  { "cat": "Networking", "name": "Network Security Group (NSG)", "icon": "🔥", "desc": "Stateful L4 firewall on subnet or NIC. 5-tuple rules.", "when": "Every subnet and every NIC. Default-deny ingress recommended.", "alt": "AWS Security Groups / GCP VPC Firewall", "price": "free" },
  { "cat": "Networking", "name": "NAT Gateway", "icon": "🚏", "desc": "Outbound-only NAT for subnets. 64K SNAT ports per public IP.", "when": "Avoid SNAT exhaustion. Predictable egress IP. AKS outbound.", "alt": "AWS NAT Gateway / GCP Cloud NAT", "price": "low" },
  { "cat": "Networking", "name": "Network Watcher", "icon": "🔍", "desc": "Network diagnostic + monitoring. Connection troubleshoot, IP Flow Verify, packet capture.", "when": "Diagnosing NSG / routing issues. Essential admin tool.", "alt": "AWS VPC Reachability Analyzer / GCP Network Intelligence Center", "price": "free" },
  { "cat": "Networking", "name": "Azure DDoS Protection", "icon": "🛡️", "desc": "DDoS attack mitigation. Network (regional) and IP Protection (single PIP) plans.", "when": "Production internet-facing apps. Basic is included free.", "alt": "AWS Shield Advanced / GCP Cloud Armor", "price": "high" },
  { "cat": "Networking", "name": "Private DNS", "icon": "📞", "desc": "Private DNS zones. Linked to VNets for FQDN resolution of private endpoints.", "when": "Always for Private Endpoint setup. Cross-VNet DNS.", "alt": "AWS Route 53 Resolver / GCP Cloud DNS Private", "price": "low" },

  // ── Azure Identity
  { "cat": "Identity", "name": "Microsoft Entra ID (formerly Azure AD)", "icon": "🆔", "desc": "Cloud identity service. Identity layer for M365 + Azure + 3rd-party SaaS.", "when": "Every Microsoft cloud customer. Free tier ships with all subscriptions.", "alt": "AWS IAM Identity Center / GCP Cloud Identity", "price": "low" },
  { "cat": "Identity", "name": "Microsoft Entra Connect", "icon": "🔄", "desc": "Sync tool from on-prem AD to Entra ID. Modes: PHS, PTA, Federation.", "when": "Any hybrid AD environment. Required for M365 hybrid.", "alt": "AWS AD Connector / GCP Cloud Directory Sync", "price": "free" },
  { "cat": "Identity", "name": "Privileged Identity Management (PIM)", "icon": "🔑", "desc": "JIT role activation. Approval workflow + access reviews + audit.", "when": "Every Global Admin should be PIM-eligible. Reduces standing privilege.", "alt": "AWS IAM Identity Center session controls / GCP IAM Conditions", "price": "mid" },
  { "cat": "Identity", "name": "Conditional Access", "icon": "🚧", "desc": "If-this-then-that rules at sign-in. User/app/device/location/risk → Grant/Block + session.", "when": "Every M365 tenant. Foundation of Zero Trust.", "alt": "AWS IAM Conditions / GCP IAM Conditions", "price": "mid" },
  { "cat": "Identity", "name": "Microsoft Entra Identity Protection", "icon": "⚠️", "desc": "Risk-based authentication. Detects compromised accounts via ML.", "when": "Real-time risk-based CA. Detects atypical travel, password spray, AiTM.", "alt": "AWS GuardDuty (different focus) / GCP no equivalent", "price": "mid" },
  { "cat": "Identity", "name": "Global Secure Access (Entra Private/Internet Access)", "icon": "🌍", "desc": "Microsoft's SSE / SASE. Replaces SSL VPN + adds CASB-like controls.", "when": "Replacing legacy VPN. Zero-trust network access.", "alt": "Zscaler / Netskope / GCP BeyondCorp", "price": "high" },
  { "cat": "Identity", "name": "Entra External ID (B2B / B2C)", "icon": "🤝", "desc": "External identity. B2B = guests in your tenant. B2C = customer identity for your app.", "when": "Partner collaboration (B2B). Customer-facing apps (B2C, separate tenant).", "alt": "AWS Cognito / GCP Firebase Auth", "price": "low" },
  { "cat": "Identity", "name": "Managed Identities", "icon": "🪪", "desc": "Azure-managed service principal for Azure resources. No secrets to rotate.", "when": "Always prefer over service principals with secrets.", "alt": "AWS IAM Role for EC2 / GCP Service Accounts", "price": "free" },
  { "cat": "Identity", "name": "Microsoft Defender for Identity (MDI)", "icon": "🕵️", "desc": "On-prem AD threat detection. Sensors on DCs. Detects pass-the-hash, golden ticket, etc.", "when": "Any org with on-prem AD. Part of Defender XDR E5 SKU.", "alt": "CrowdStrike / Vectra AI", "price": "mid" },

  // ── Azure Databases
  { "cat": "Database", "name": "Azure SQL Database", "icon": "🗄️", "desc": "PaaS SQL Server. DTU or vCore. Service tiers: Basic / Standard / GP / BC / Hyperscale.", "when": "New SQL Server workloads. Most managed option.", "alt": "AWS RDS for SQL Server / GCP Cloud SQL", "price": "mid" },
  { "cat": "Database", "name": "Azure SQL Managed Instance (SQL MI)", "icon": "🗄️", "desc": "PaaS SQL Server with full engine features. Cross-DB queries, SQL Agent, CLR.", "when": "Migrating from on-prem SQL Server. Need SQL Agent / cross-DB features.", "alt": "AWS RDS for SQL Server / GCP Cloud SQL Premium", "price": "high" },
  { "cat": "Database", "name": "Azure SQL Database Hyperscale", "icon": "🗄️", "desc": "SQL DB tier supporting up to 100 TB + many read replicas. Page server architecture.", "when": "Single DBs > 4 TB. Read-heavy with read scale-out.", "alt": "AWS Aurora / GCP AlloyDB", "price": "high" },
  { "cat": "Database", "name": "Azure Cosmos DB", "icon": "🌌", "desc": "Globally distributed NoSQL. APIs: SQL (Core), MongoDB, Cassandra, Gremlin, Table.", "when": "Multi-region writes, low-latency global apps, IoT telemetry.", "alt": "AWS DynamoDB Global Tables / GCP Spanner", "price": "high" },
  { "cat": "Database", "name": "Azure Database for PostgreSQL", "icon": "🐘", "desc": "Managed PostgreSQL. Flexible Server (recommended) or Single Server (legacy).", "when": "PostgreSQL workloads. Open-source preference.", "alt": "AWS RDS for PostgreSQL / Aurora / GCP Cloud SQL", "price": "mid" },
  { "cat": "Database", "name": "Azure Database for MySQL", "icon": "🐬", "desc": "Managed MySQL. Flexible Server tier.", "when": "MySQL workloads. WordPress, LAMP stacks.", "alt": "AWS RDS for MySQL / Aurora / GCP Cloud SQL", "price": "mid" },
  { "cat": "Database", "name": "Azure Cache for Redis", "icon": "⚡", "desc": "Managed Redis. Basic / Standard / Premium / Enterprise tiers. Active geo-replication on Enterprise.", "when": "Session state, distributed cache, real-time leaderboards, pub/sub.", "alt": "AWS ElastiCache / GCP Memorystore", "price": "mid" },
  { "cat": "Database", "name": "Azure Database for MariaDB (retiring)", "icon": "🐬", "desc": "Managed MariaDB. <del>Retiring Sept 2025.</del>", "when": "Migrate to PostgreSQL or Azure Database for MySQL.", "alt": "AWS RDS for MariaDB / GCP no native", "price": "free" },
  { "cat": "Database", "name": "Azure Database for PostgreSQL Cosmos DB", "icon": "🐘", "desc": "Cosmos DB with PostgreSQL wire protocol. Sharded PostgreSQL distributed table.", "when": "PostgreSQL workloads needing horizontal scale (citus extension).", "alt": "AWS Aurora PostgreSQL / GCP AlloyDB", "price": "high" },

  // ── Azure Data + Analytics
  { "cat": "Data + Analytics", "name": "Azure Synapse Analytics", "icon": "📊", "desc": "Cloud data warehouse + Spark + SQL pools + pipelines. Unified analytics.", "when": "Enterprise data warehouse. Mix of SQL + Spark + streaming.", "alt": "AWS Redshift / GCP BigQuery", "price": "high" },
  { "cat": "Data + Analytics", "name": "Azure Data Factory (ADF)", "icon": "🏭", "desc": "Code-low ETL/ELT pipelines. Visual pipeline designer. 90+ connectors.", "when": "Move + transform data between sources. Schedule jobs.", "alt": "AWS Glue / GCP Cloud Data Fusion", "price": "mid" },
  { "cat": "Data + Analytics", "name": "Azure Databricks", "icon": "🧱", "desc": "Managed Apache Spark + Delta Lake. Notebooks. Auto-scale clusters.", "when": "Data engineering, ML training, real-time analytics at scale.", "alt": "AWS EMR + Databricks on AWS / GCP Dataproc", "price": "high" },
  { "cat": "Data + Analytics", "name": "Azure Stream Analytics", "icon": "🌊", "desc": "Real-time stream processing. SQL-like queries on streaming data.", "when": "IoT telemetry, real-time dashboards, fraud detection streams.", "alt": "AWS Kinesis Data Analytics / GCP Dataflow", "price": "mid" },
  { "cat": "Data + Analytics", "name": "Event Hubs", "icon": "🎫", "desc": "Big data streaming + ingestion. Millions of events per second. Kafka API.", "when": "Event ingestion pipelines. App telemetry. Replaces Kafka for many.", "alt": "AWS Kinesis Data Streams / GCP Pub/Sub", "price": "mid" },
  { "cat": "Data + Analytics", "name": "Event Grid", "icon": "📡", "desc": "Pub/sub event routing. Built-in events for every Azure service.", "when": "React to Azure service events. Decouple producers + consumers.", "alt": "AWS EventBridge / GCP Eventarc", "price": "low" },
  { "cat": "Data + Analytics", "name": "Azure Data Explorer (ADX) / Kusto", "icon": "🔬", "desc": "Time-series + log analytics database. Powers Log Analytics + Sentinel.", "when": "Massive log volumes, time-series, IoT analytics. KQL queries.", "alt": "AWS OpenSearch Service / GCP no direct equivalent", "price": "mid" },
  { "cat": "Data + Analytics", "name": "Microsoft Fabric", "icon": "🧵", "desc": "Unified SaaS analytics platform. Bundle of Synapse + Power BI + Data Factory + OneLake.", "when": "New analytics deployments. End-to-end SaaS analytics for non-tech teams.", "alt": "Snowflake / Databricks Lakehouse Platform", "price": "high" },
  { "cat": "Data + Analytics", "name": "Power BI", "icon": "📈", "desc": "Business analytics + reporting. Self-service dashboards. Embeds in M365.", "when": "Enterprise BI + reporting. Pair with Excel for finance teams.", "alt": "AWS QuickSight / GCP Looker", "price": "low" },

  // ── Azure AI + ML
  { "cat": "AI + ML", "name": "Azure OpenAI Service", "icon": "🤖", "desc": "GPT-4o + DALL-E + Whisper + reasoning models hosted in your Azure tenant. Data residency.", "when": "Enterprise GenAI apps. Compliance / data residency requirements.", "alt": "OpenAI direct API / AWS Bedrock (Claude) / GCP Vertex (Gemini)", "price": "mid" },
  { "cat": "AI + ML", "name": "Azure AI Foundry (was Azure AI Studio)", "icon": "🏗️", "desc": "Full ML platform. Models, Prompt Flow, Fine-tuning, Evaluations, Content Safety.", "when": "Build + deploy production GenAI. Multi-model orchestration.", "alt": "AWS Bedrock + SageMaker / GCP Vertex AI", "price": "mid" },
  { "cat": "AI + ML", "name": "Azure AI Search (was Cognitive Search)", "icon": "🔍", "desc": "Managed search + vector store. Hybrid (BM25 + vector). Semantic ranker.", "when": "RAG patterns. Site search. Knowledge bases.", "alt": "AWS OpenSearch Service / GCP Vertex AI Search", "price": "mid" },
  { "cat": "AI + ML", "name": "Azure Machine Learning (Azure ML)", "icon": "🧠", "desc": "End-to-end ML lifecycle. Training, deployment, MLOps.", "when": "Traditional ML (non-LLM). Custom model training. AutoML.", "alt": "AWS SageMaker / GCP Vertex AI", "price": "mid" },
  { "cat": "AI + ML", "name": "Azure Cognitive Services", "icon": "🎯", "desc": "Pre-built AI APIs: Vision, Speech, Language, Decision. Now part of Azure AI Services.", "when": "OCR, sentiment, translation, custom vision — without training your own model.", "alt": "AWS Rekognition / Translate / Comprehend / GCP Vision / Translate / NL API", "price": "low" },
  { "cat": "AI + ML", "name": "Microsoft Copilot Studio", "icon": "💬", "desc": "Build copilots / chatbots. Knowledge sources, actions via Power Automate, channels.", "when": "Internal IT helpdesk bots. Customer service. FAQ bots.", "alt": "AWS Amazon Q / GCP Conversational Agents", "price": "low" },

  // ── M365
  { "cat": "M365", "name": "Microsoft 365 Apps for Enterprise", "icon": "📝", "desc": "Word, Excel, PowerPoint, Outlook, OneNote, Teams. Click-to-Run, semi-annual + monthly channels.", "when": "All knowledge workers. Bundle in E3/E5 licences.", "alt": "Google Workspace / LibreOffice", "price": "low" },
  { "cat": "M365", "name": "Exchange Online", "icon": "✉️", "desc": "Cloud email service. 100 GB / mailbox standard. Hybrid coexistence with on-prem.", "when": "Replace on-prem Exchange. Every M365 tenant has it.", "alt": "Google Workspace / SendGrid (transactional)", "price": "low" },
  { "cat": "M365", "name": "SharePoint Online", "icon": "🗂️", "desc": "Document management + intranet. Sites, libraries, lists, hub sites, search.", "when": "Team collaboration. Modern intranet. Document storage.", "alt": "Google Sites / Confluence", "price": "low" },
  { "cat": "M365", "name": "OneDrive for Business", "icon": "☁️", "desc": "Per-user cloud storage. 1 TB+ per user. Known folder sync.", "when": "User backup + access from anywhere. Replaces home shares.", "alt": "Google Drive / Box / Dropbox", "price": "low" },
  { "cat": "M365", "name": "Microsoft Teams", "icon": "💬", "desc": "Chat + meetings + calling. Phone System (Direct Routing / Calling Plans).", "when": "Internal comms, meetings, replace Skype + Slack.", "alt": "Slack / Zoom / Google Meet", "price": "low" },
  { "cat": "M365", "name": "Microsoft Forms", "icon": "📋", "desc": "Quick surveys + quizzes. Integration with SharePoint + Teams.", "when": "Surveys, quizzes, simple data collection.", "alt": "Google Forms / Typeform", "price": "free" },
  { "cat": "M365", "name": "Microsoft Lists", "icon": "📑", "desc": "Lightweight structured lists. Built on SharePoint Lists.", "when": "Issue trackers, asset registers, simple databases for teams.", "alt": "Google Sheets / Airtable", "price": "low" },
  { "cat": "M365", "name": "Microsoft Loop", "icon": "🔄", "desc": "Co-authoring components. Embeds in Teams chats + Outlook.", "when": "Cross-app collaboration. Decision tracking.", "alt": "Notion / Coda", "price": "low" },
  { "cat": "M365", "name": "Microsoft Viva", "icon": "🌟", "desc": "Employee experience suite. Insights, Learning, Engage, Topics, Goals.", "when": "Employee engagement, learning platforms, internal social.", "alt": "Workday Peakon / LinkedIn Learning", "price": "mid" },
  { "cat": "M365", "name": "Microsoft Defender for Office 365", "icon": "🛡️", "desc": "Email + collab threat protection. Safe Links, Safe Attachments, anti-phishing.", "when": "Every M365 tenant. P2 adds Attack Simulator + Threat Tracker.", "alt": "Proofpoint / Mimecast / Cisco Cloud Email Security", "price": "mid" },
  { "cat": "M365", "name": "Microsoft Defender XDR", "icon": "🛡️", "desc": "Unified XDR portal. Cross-domain (endpoint + identity + email + cloud apps) incident correlation.", "when": "M365 E5 customers. Replaces Microsoft 365 Defender brand.", "alt": "CrowdStrike Falcon / SentinelOne Singularity", "price": "high" },
  { "cat": "M365", "name": "Microsoft Sentinel", "icon": "🛡️", "desc": "Cloud-native SIEM + SOAR. KQL queries, analytics rules, playbooks via Logic Apps.", "when": "Cross-tool SIEM. Multi-tenant SOC (MSSP) with Workspace Manager.", "alt": "Splunk / QRadar / Elastic Security / GCP Chronicle", "price": "high" },
  { "cat": "M365", "name": "Microsoft Intune", "icon": "📱", "desc": "Cloud MDM + MAM. Windows, macOS, iOS, Android. Autopilot, Compliance, Conditional Access.", "when": "Modern endpoint management. Replace SCCM gradually via co-management.", "alt": "VMware Workspace ONE / Jamf / Mosyle", "price": "low" },
  { "cat": "M365", "name": "Microsoft Purview", "icon": "🛡️", "desc": "Data governance + compliance. DLP, Labels, eDiscovery, IRM, Audit, Data Map.", "when": "Regulated industries. GDPR / DPDP / HIPAA / SOX compliance.", "alt": "Varonis / OneTrust / Collibra (data governance)", "price": "mid" },
  { "cat": "M365", "name": "Power Platform", "icon": "⚡", "desc": "Low-code suite: Power Apps + Power Automate + Power BI + Power Pages + Copilot Studio + Dataverse.", "when": "Citizen developers + IT building line-of-business apps quickly.", "alt": "Salesforce Lightning Platform / OutSystems / Mendix", "price": "low" },

  // ── DevOps + Automation
  { "cat": "DevOps", "name": "Azure DevOps", "icon": "🛠️", "desc": "CI/CD + Boards + Repos + Test Plans + Artifacts. Microsoft's git + pipelines.", "when": "Enterprise CI/CD. Mature, deep integration with Azure.", "alt": "GitHub Actions / GitLab / Bitbucket Pipelines", "price": "low" },
  { "cat": "DevOps", "name": "GitHub (Enterprise + Actions)", "icon": "🐙", "desc": "Code hosting + CI/CD. Microsoft-owned. Largest dev community.", "when": "Modern CI/CD. Open-source preference. Best ecosystem.", "alt": "Azure DevOps / GitLab", "price": "low" },
  { "cat": "DevOps", "name": "Azure Bicep", "icon": "💪", "desc": "DSL for Azure ARM templates. Cleaner than JSON. Compiles to ARM.", "when": "Azure-only IaC. Native, no state file.", "alt": "Terraform / Pulumi / AWS CloudFormation", "price": "free" },
  { "cat": "DevOps", "name": "Azure Resource Manager (ARM)", "icon": "🏛️", "desc": "Azure deployment + management API. Underlying API for everything.", "when": "When using ARM JSON templates directly. Mostly via Bicep now.", "alt": "AWS CloudFormation / GCP Deployment Manager", "price": "free" },
  { "cat": "DevOps", "name": "Terraform (HashiCorp)", "icon": "🟪", "desc": "Multi-cloud IaC. HCL syntax. State file. Works on Azure, AWS, GCP, 100+ providers.", "when": "Multi-cloud teams. Existing Terraform investment.", "alt": "Bicep (Azure-only) / Pulumi (TS/Go)", "price": "free" },
  { "cat": "DevOps", "name": "Azure Container Registry (ACR)", "icon": "📦", "desc": "Managed Docker registry. Geo-replication, vulnerability scanning, trusted signing.", "when": "AKS image hosting. CI/CD push targets.", "alt": "AWS ECR / GCP Artifact Registry / Docker Hub", "price": "low" },
  { "cat": "DevOps", "name": "Azure Monitor", "icon": "📊", "desc": "Metrics + logs + traces + alerts. Unified observability platform.", "when": "Every Azure deployment. Send everything to one workspace.", "alt": "AWS CloudWatch / GCP Cloud Monitoring", "price": "mid" },
  { "cat": "DevOps", "name": "Application Insights", "icon": "📊", "desc": "APM for web apps + microservices. Auto-instrumentation. Smart detection.", "when": "Every web app. .NET / Node / Python / Java first-class.", "alt": "AWS X-Ray / GCP Cloud Trace / Datadog APM", "price": "mid" },
  { "cat": "DevOps", "name": "Log Analytics Workspace", "icon": "📊", "desc": "Underlying storage for Azure Monitor logs. Kusto / KQL queries.", "when": "Centralised log storage. Sentinel runs on top.", "alt": "AWS CloudWatch Logs / GCP Cloud Logging", "price": "mid" },
  { "cat": "DevOps", "name": "Azure Automation", "icon": "⚙️", "desc": "Runbooks (PowerShell, Python). Update Management (now Update Manager). State Configuration.", "when": "Scheduled tasks, runbooks, configuration enforcement.", "alt": "AWS Systems Manager / GCP Workflows", "price": "free" },
  { "cat": "DevOps", "name": "Azure Logic Apps", "icon": "🔌", "desc": "Workflow orchestrator with 400+ connectors. Consumption + Standard tiers.", "when": "No-code workflow automation. Connect SaaS apps. Sentinel SOAR.", "alt": "AWS Step Functions / GCP Workflows / Zapier", "price": "low" },

  // ── Security + Governance
  { "cat": "Security", "name": "Microsoft Defender for Cloud", "icon": "🛡️", "desc": "CSPM + CWP for Azure / AWS / GCP. Plans per resource type.", "when": "Production cloud workloads. Free tier = posture only.", "alt": "AWS Security Hub / GCP Security Command Center / Wiz / Prisma Cloud", "price": "mid" },
  { "cat": "Security", "name": "Defender for Servers", "icon": "🖥️", "desc": "EDR + vulnerability assessment for VMs (incl. on-prem via Arc). Plan 1 + 2.", "when": "Production VMs. Plan 2 adds JIT VM Access + free Defender for Endpoint.", "alt": "CrowdStrike / SentinelOne / Microsoft Defender for Endpoint standalone", "price": "mid" },
  { "cat": "Security", "name": "Defender for SQL", "icon": "🗄️", "desc": "Vulnerability assessment + Advanced Threat Protection for SQL DB / SQL MI.", "when": "Production SQL databases.", "alt": "AWS RDS native / GCP Cloud SQL native", "price": "low" },
  { "cat": "Security", "name": "Defender for Storage", "icon": "🗃️", "desc": "Malware scanning + sensitive data discovery for Blob / Files / Data Lake.", "when": "Production storage accounts with sensitive data.", "alt": "AWS Macie (Sensitive data) / GCP DLP", "price": "mid" },
  { "cat": "Security", "name": "Defender for Containers", "icon": "📦", "desc": "AKS runtime threat protection + image scanning + Admission control.", "when": "Production AKS. Detects crypto miners, privileged containers.", "alt": "Aqua Security / Sysdig Secure / GCP Container Threat Detection", "price": "mid" },
  { "cat": "Security", "name": "Defender for Key Vault", "icon": "🔑", "desc": "Detects anomalous Key Vault access. Brute force, key dump.", "when": "Production Key Vaults with secrets / certs.", "alt": "AWS Secrets Manager + GuardDuty / GCP no native", "price": "low" },
  { "cat": "Security", "name": "Azure Policy", "icon": "⚖️", "desc": "Governance engine. Define rules. Effects: Audit / Deny / Modify / DeployIfNotExists.", "when": "Every subscription. Enforce tagging, region, SKU limits.", "alt": "AWS Config / GCP Organization Policy", "price": "free" },
  { "cat": "Security", "name": "Azure Blueprints (deprecated)", "icon": "📐", "desc": "Bundle of policies + role assignments + RGs. <del>Deprecated July 2026</del>. Migrate to Template Specs + Deployment Stacks.", "when": "Migrate existing blueprints.", "alt": "AWS Control Tower / GCP Cloud Foundation Toolkit", "price": "free" },
  { "cat": "Security", "name": "Azure Key Vault", "icon": "🔐", "desc": "Centralized secret + key + cert store. Standard + Premium (HSM-backed).", "when": "Every app. Use Key Vault references in App Service / Function App config.", "alt": "AWS Secrets Manager + KMS / GCP Secret Manager + KMS", "price": "low" },
  { "cat": "Security", "name": "Azure Managed HSM", "icon": "🔐", "desc": "FIPS 140-3 Level 3 dedicated HSM. Customer-owned single-tenant.", "when": "Strict compliance (PCI HSM, government). High-volume crypto operations.", "alt": "AWS CloudHSM / GCP Cloud HSM", "price": "high" },

  // ── Integration + APIs
  { "cat": "Integration", "name": "Azure API Management (APIM)", "icon": "🔌", "desc": "API gateway + developer portal + analytics. Consumption / Basic / Standard / Premium.", "when": "Expose internal APIs to partners. Rate limiting. Multi-region.", "alt": "AWS API Gateway / GCP Apigee", "price": "mid" },
  { "cat": "Integration", "name": "Azure Service Bus", "icon": "🚌", "desc": "Enterprise messaging. Queues + topics with FIFO + duplicate detection.", "when": "Enterprise app messaging. Order-sensitive, transactional patterns.", "alt": "AWS SQS / GCP Pub/Sub", "price": "mid" },
  { "cat": "Integration", "name": "Azure Storage Queues", "icon": "📋", "desc": "Lightweight queue on Storage account. Simple HTTP.", "when": "Simple async tasks. Cheap. Not for ordering or large messages.", "alt": "AWS SQS / GCP Cloud Tasks", "price": "low" },
  { "cat": "Integration", "name": "Azure Web PubSub", "icon": "📡", "desc": "Real-time WebSocket service. Built on SignalR Service.", "when": "Live dashboards, chat apps, online gaming.", "alt": "AWS API Gateway WebSockets / GCP no native", "price": "low" }
];
