"use client";

import { useState } from "react";
import { toast } from "sonner";

import type { M365Action } from "@/lib/labs/simulators/m365/reducer";
import type { M365OfficeDeployConfig, M365State } from "@/lib/labs/simulators/m365/types";
import { FormGroup, Pill } from "./m365-ui";
import styles from "./m365-console.module.css";

type DeploySub = "config" | "xml" | "options";

const UPDATE_CHANNELS: { id: M365OfficeDeployConfig["updateChannel"]; desc: string }[] = [
  { id: "Current", desc: "Latest features as they release (~monthly). Pilot / IT." },
  { id: "Monthly Enterprise", desc: "Latest features on the 2nd Tuesday each month. Mainstream production. Recommended." },
  { id: "Semi-Annual Enterprise", desc: "Most stable — released January and July. Validation-heavy orgs." },
  { id: "Semi-Annual Enterprise (Preview)", desc: "Preview of the next Semi-Annual Enterprise release — March and September." },
  { id: "Current Preview", desc: "Preview of the next Current Channel release." },
  { id: "Beta", desc: "Weekly Insider builds. Pre-release testing only." },
];

const PRODUCTS = ["Microsoft 365 Apps for enterprise", "Microsoft 365 Apps for business", "Visio", "Project"];

const EXCLUDABLE_APPS = [
  "Access",
  "Excel",
  "Groove",
  "Skype for Business",
  "OneDrive",
  "OneNote",
  "Outlook",
  "PowerPoint",
  "Publisher",
  "SharePoint Designer",
  "Teams",
  "Word",
  "Bing",
];

const LANGUAGES = [
  "English (United States)",
  "English (United Kingdom)",
  "Hindi (India)",
  "Tamil (India)",
  "Telugu (India)",
  "German (Germany)",
  "French (France)",
  "Spanish (Spain)",
  "Japanese (Japan)",
  "Chinese (Simplified)",
];

function xmlEscape(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function buildConfigXml(config: M365OfficeDeployConfig): string {
  const officeClientEdition = config.architecture === "64-bit" ? "64" : "32";
  const langLines = config.languages.map((l) => `      <Language ID="${xmlEscape(l)}" />`).join("\n");
  const excludeLines = config.excludedApps.map((a) => `      <ExcludeApp ID="${xmlEscape(a)}" />`).join("\n");
  const productLines = config.products
    .map((p) => {
      const isAddOn = p === "Visio" || p === "Project";
      return `    <Product ID="${isAddOn ? p : "O365ProPlusRetail"}">\n${langLines}${!isAddOn && excludeLines ? `\n${excludeLines}` : ""}\n    </Product>`;
    })
    .join("\n");

  const lines: string[] = [];
  lines.push(`<Configuration ID="${xmlEscape(config.deploymentName).slice(0, 64)}">`);
  lines.push(`  <Info Description="Generated by ITBD Labs — config.office.com mirror" />`);
  lines.push(
    `  <Add OfficeClientEdition="${officeClientEdition}" Channel="${xmlEscape(config.updateChannel)}" MigrateArch="${config.migrateArch ? "TRUE" : "FALSE"}" SourcePath="${config.source === "CDN" ? "" : "\\\\fileshare\\Office"}">`,
  );
  lines.push(productLines);
  lines.push(`  </Add>`);
  lines.push(`  <Updates Enabled="${config.updateSettings.autoUpdate ? "TRUE" : "FALSE"}" />`);
  lines.push(`  <Display Level="${config.installOptions.silent ? "None" : "Full"}" AcceptEULA="TRUE" />`);
  if (config.orgName) lines.push(`  <Property Name="COMPANYNAME" Value="${xmlEscape(config.orgName)}" />`);
  lines.push(`  <Property Name="AUTOACTIVATE" Value="1" />`);
  if (config.installOptions.forceUpgrade) lines.push(`  <Property Name="FORCEAPPSHUTDOWN" Value="TRUE" />`);
  if (config.installOptions.removeMsi) lines.push(`  <RemoveMSI />`);
  lines.push(`</Configuration>`);
  return lines.join("\n") + "\n";
}

export function AppsDeployPage({ state, dispatch }: { state: M365State; dispatch: (action: M365Action) => void }) {
  const [sub, setSub] = useState<DeploySub>("config");
  const config = state.officeDeploy;

  function patch(p: Partial<M365OfficeDeployConfig>) {
    dispatch({ type: "UPDATE_OFFICE_DEPLOY", patch: p });
  }

  function toggleInList(list: string[], value: string): string[] {
    return list.includes(value) ? list.filter((v) => v !== value) : [...list, value];
  }

  function toggleProduct(value: string) {
    const next = toggleInList(config.products, value);
    patch({ products: next.length ? next : config.products });
  }

  function toggleExcludedApp(value: string) {
    patch({ excludedApps: toggleInList(config.excludedApps, value) });
  }

  function toggleLanguage(value: string) {
    const next = toggleInList(config.languages, value);
    if (!next.length) {
      toast.error("At least one language is required.");
      return;
    }
    patch({ languages: next });
  }

  async function copyXml() {
    await navigator.clipboard.writeText(buildConfigXml(config));
    toast.success("Config XML copied to clipboard.");
  }

  function downloadXml() {
    const blob = new Blob([buildConfigXml(config)], { type: "application/xml" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "config.xml";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Downloaded config.xml");
  }

  async function copyInstallCommand() {
    await navigator.clipboard.writeText("setup.exe /configure config.xml");
    toast.success("Install command copied.");
  }

  return (
    <div>
      <h1 className={styles.pageH1}>Microsoft 365 Apps install</h1>
      <p className={styles.pageSub}>
        Build a deployment configuration for the Office Deployment Tool (ODT). Download the XML, then run <code>setup.exe /configure config.xml</code> on the target device.
      </p>

      <div className={styles.subtabs}>
        <button type="button" className={`${styles.subtab} ${sub === "config" ? styles.subtabActive : ""}`} onClick={() => setSub("config")}>
          Configuration
        </button>
        <button type="button" className={`${styles.subtab} ${sub === "xml" ? styles.subtabActive : ""}`} onClick={() => setSub("xml")}>
          Generated XML
        </button>
        <button type="button" className={`${styles.subtab} ${sub === "options" ? styles.subtabActive : ""}`} onClick={() => setSub("options")}>
          Deployment options
        </button>
      </div>

      {sub === "config" ? (
        <div>
          <div className={styles.h2}>Deployment name</div>
          <div className={styles.card}>
            <FormGroup label="Deployment name">
              <input className={styles.input} value={config.deploymentName} onChange={(e) => patch({ deploymentName: e.target.value })} />
            </FormGroup>
          </div>

          <div className={styles.h2}>Update channel</div>
          <div className={styles.card}>
            {UPDATE_CHANNELS.map((c) => (
              <label key={c.id} className={styles.radioRow} style={{ alignItems: "flex-start" }}>
                <input type="radio" name="updateChannel" checked={config.updateChannel === c.id} onChange={() => patch({ updateChannel: c.id })} />
                <span>
                  <strong>{c.id}</strong>
                  <div className={styles.formHelp}>{c.desc}</div>
                </span>
              </label>
            ))}
          </div>

          <div className={styles.h2}>Architecture</div>
          <div className={styles.card}>
            <label className={styles.radioRow}>
              <input type="radio" name="arch" checked={config.architecture === "64-bit"} onChange={() => patch({ architecture: "64-bit" })} />
              <strong>64-bit</strong> (recommended for &gt; 4 GB RAM, large files)
            </label>
            <label className={styles.radioRow}>
              <input type="radio" name="arch" checked={config.architecture === "32-bit"} onChange={() => patch({ architecture: "32-bit" })} />
              <strong>32-bit</strong> (only if you have 32-bit COM add-ins)
            </label>
            <label className={styles.checkboxRow}>
              <input type="checkbox" checked={config.migrateArch} onChange={(e) => patch({ migrateArch: e.target.checked })} />
              Migrate existing installs to this architecture
            </label>
          </div>

          <div className={styles.h2}>Apps to install</div>
          <div className={styles.card}>
            {PRODUCTS.map((p) => (
              <label key={p} className={styles.checkboxRow}>
                <input type="checkbox" checked={config.products.includes(p)} onChange={() => toggleProduct(p)} />
                {p}
              </label>
            ))}
          </div>

          <div className={styles.h2}>Exclude these apps</div>
          <div className={styles.card}>
            <div style={{ columns: "3 200px", columnGap: 24 }}>
              {EXCLUDABLE_APPS.map((a) => (
                <label key={a} className={styles.checkboxRow} style={{ breakInside: "avoid" }}>
                  <input type="checkbox" checked={config.excludedApps.includes(a)} onChange={() => toggleExcludedApp(a)} />
                  {a}
                </label>
              ))}
            </div>
          </div>

          <div className={styles.h2}>Languages</div>
          <div className={styles.card}>
            <div style={{ columns: "3 200px", columnGap: 24 }}>
              {LANGUAGES.map((l) => (
                <label key={l} className={styles.checkboxRow} style={{ breakInside: "avoid" }}>
                  <input type="checkbox" checked={config.languages.includes(l)} onChange={() => toggleLanguage(l)} />
                  {l}
                </label>
              ))}
            </div>
          </div>

          <div className={styles.h2}>Installation options</div>
          <div className={styles.card}>
            <label className={styles.checkboxRow}>
              <input type="checkbox" checked={config.installOptions.silent} onChange={(e) => patch({ installOptions: { ...config.installOptions, silent: e.target.checked } })} />
              Silent install (no UI shown to the user)
            </label>
            <label className={styles.checkboxRow}>
              <input
                type="checkbox"
                checked={config.installOptions.forceUpgrade}
                onChange={(e) => patch({ installOptions: { ...config.installOptions, forceUpgrade: e.target.checked } })}
              />
              Force shut down running Office apps during install
            </label>
            <label className={styles.checkboxRow}>
              <input type="checkbox" checked={config.installOptions.removeMsi} onChange={(e) => patch({ installOptions: { ...config.installOptions, removeMsi: e.target.checked } })} />
              Remove MSI versions of Office if found
            </label>
          </div>

          <div className={styles.h2}>Update settings</div>
          <div className={styles.card}>
            <label className={styles.checkboxRow}>
              <input
                type="checkbox"
                checked={config.updateSettings.autoUpdate}
                onChange={(e) => patch({ updateSettings: { ...config.updateSettings, autoUpdate: e.target.checked } })}
              />
              Automatically update Office apps
            </label>
          </div>

          <div className={styles.h2}>Source files</div>
          <div className={styles.card}>
            <label className={styles.radioRow}>
              <input type="radio" name="source" checked={config.source === "CDN"} onChange={() => patch({ source: "CDN" })} />
              Office CDN (Microsoft delivery network — internet required)
            </label>
            <label className={styles.radioRow}>
              <input type="radio" name="source" checked={config.source === "Local network share"} onChange={() => patch({ source: "Local network share" })} />
              Local network share (UNC path — for offline install)
            </label>
          </div>

          <div className={styles.h2}>Organization branding</div>
          <div className={styles.card}>
            <FormGroup label="Organization name">
              <input className={styles.input} value={config.orgName} onChange={(e) => patch({ orgName: e.target.value })} />
            </FormGroup>
          </div>
        </div>
      ) : null}

      {sub === "xml" ? (
        <div>
          <div className={styles.card}>
            Save this XML as <code>config.xml</code>, then run <code>setup.exe /configure config.xml</code> on the target device. <Pill tone="info">ODT required</Pill>
          </div>
          <pre className={styles.codeBlock}>{buildConfigXml(config)}</pre>
          <div className={styles.toolbar}>
            <button type="button" className={styles.tbBtn} onClick={copyXml}>
              Copy to clipboard
            </button>
            <button type="button" className={styles.tbBtn} onClick={downloadXml}>
              Download config.xml
            </button>
          </div>
        </div>
      ) : null}

      {sub === "options" ? (
        <div>
          <div className={styles.h2}>Bandwidth and install size estimates</div>
          <div className={styles.tableWrap}>
            <table className={styles.table}>
              <thead>
                <tr>
                  <th>Component</th>
                  <th>Approx. download (per 100 users)</th>
                  <th>Disk after install</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Base 64-bit Microsoft 365 Apps for enterprise</td>
                  <td>~200 GB</td>
                  <td>6.5 GB per device</td>
                </tr>
                <tr>
                  <td>Each additional language</td>
                  <td>~25 GB</td>
                  <td>~600 MB per device</td>
                </tr>
                <tr>
                  <td>Visio</td>
                  <td>~50 GB</td>
                  <td>1.6 GB per device</td>
                </tr>
                <tr>
                  <td>Project</td>
                  <td>~50 GB</td>
                  <td>1.6 GB per device</td>
                </tr>
                <tr>
                  <td>Monthly updates (average)</td>
                  <td>~15 GB</td>
                  <td>n/a</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className={styles.h2}>Recommended distribution methods</div>
          <div className={styles.cardGrid}>
            <div className={styles.tile}>
              <div className={styles.tileTitle}>Local network share</div>
              <div className={styles.tileSub}>Place setup.exe and config.xml on a share for offline / low-bandwidth sites. Trigger via logon script or GPO.</div>
            </div>
            <div className={styles.tile}>
              <div className={styles.tileTitle}>Office CDN</div>
              <div className={styles.tileSub}>Devices pull install and update bits directly from Microsoft's delivery network. Simplest option for internet-connected devices.</div>
            </div>
            <div className={styles.tile}>
              <div className={styles.tileTitle}>Configuration Manager</div>
              <div className={styles.tileSub}>Best for on-prem managed devices and co-managed estates. ConfigMgr's Microsoft 365 Apps wizard consumes this config.xml.</div>
            </div>
          </div>

          <div className={styles.h2}>Install command</div>
          <pre className={styles.codeBlock}>setup.exe /configure config.xml</pre>
          <div className={styles.toolbar}>
            <button type="button" className={styles.tbBtn} onClick={copyInstallCommand}>
              Copy install command
            </button>
          </div>

          <div className={styles.h2}>Verify after install</div>
          <pre className={styles.codeBlock}>{`Get-Item "C:\\Program Files\\Microsoft Office\\root\\Office16\\ONENOTE.EXE" | Select-Object VersionInfo

# Check installed channel + version
Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Office\\ClickToRun\\Configuration" |
  Select-Object CDNBaseUrl, VersionToReport`}</pre>
        </div>
      ) : null}
    </div>
  );
}
