import type { AddsState } from "./types";

export function freshAddsState(): AddsState {
  return {
    domain: {
      fqdn: "corp.cloudlab.local",
      netbios: "CORP",
      forestFunctionalLevel: "Windows Server 2022",
      domainFunctionalLevel: "Windows Server 2022",
      forestRoot: "corp.cloudlab.local",
      schemaMaster: "DC01.corp.cloudlab.local",
      domainNamingMaster: "DC01.corp.cloudlab.local",
      pdcEmulator: "DC01.corp.cloudlab.local",
      ridMaster: "DC01.corp.cloudlab.local",
      infrastructureMaster: "DC02.corp.cloudlab.local",
    },
    sites: [{ name: "Default-First-Site-Name", subnets: ["192.168.1.0/24"] }],
    domainControllers: [
      { name: "DC01", os: "Windows Server 2022 Datacenter", site: "Default-First-Site-Name", ip: "192.168.1.10", isGC: true, isPDC: true, roles: ["AD DS", "DNS", "GC"] },
      { name: "DC02", os: "Windows Server 2022 Datacenter", site: "Default-First-Site-Name", ip: "192.168.1.11", isGC: true, isPDC: false, roles: ["AD DS", "DNS", "GC"] },
    ],
    ous: [
      { name: "_Users", parent: null, description: "Standard user accounts" },
      { name: "_Computers", parent: null, description: "Workstation and laptop accounts" },
      { name: "_ServiceAccounts", parent: null, description: "Service principals and gMSA" },
      { name: "_Disabled", parent: null, description: "Disabled accounts pending deletion" },
      { name: "IT", parent: null, description: "IT department" },
      { name: "Sales", parent: null, description: "Sales department" },
      { name: "Marketing", parent: null, description: "Marketing department" },
      { name: "Finance", parent: null, description: "Finance department" },
    ],
    builtInContainers: [
      { name: "Builtin", type: "builtinDomain" },
      { name: "Computers", type: "container" },
      { name: "Domain Controllers", type: "organizationalUnit" },
      { name: "ForeignSecurityPrincipals", type: "container" },
      { name: "Managed Service Accounts", type: "container" },
      { name: "Users", type: "container" },
    ],
    users: [
      {
        sAMAccountName: "admin",
        upn: "admin@corp.cloudlab.local",
        name: "admin",
        givenName: "Domain",
        surname: "Admin",
        initials: "",
        displayName: "Domain Administrator",
        email: "admin@corp.cloudlab.local",
        department: "IT",
        title: "Administrator",
        manager: "",
        office: "",
        phone: "",
        mobile: "",
        streetAddress: "",
        city: "",
        state: "",
        zip: "",
        country: "IN",
        description: "Built-in domain administrator",
        memberOf: ["Domain Admins", "Enterprise Admins", "Schema Admins", "Administrators", "Domain Users"],
        enabled: true,
        locked: false,
        mustChangePassword: false,
        cantChangePassword: false,
        neverExpires: true,
        passwordLastSet: "2024-01-10T08:00:00Z",
        lastLogon: "2025-03-12T09:42:00Z",
        created: "2024-01-10T08:00:00Z",
        ouPath: "Users",
        logonHours: "All",
        logonTo: "All computers",
        profilePath: "",
        loginScript: "",
        homeDir: "",
        homeDrive: "",
      },
      {
        sAMAccountName: "jdoe",
        upn: "jdoe@corp.cloudlab.local",
        name: "jdoe",
        givenName: "John",
        surname: "Doe",
        initials: "J.D.",
        displayName: "John Doe",
        email: "jdoe@corp.cloudlab.local",
        department: "Sales",
        title: "Account Executive",
        manager: "ksmith",
        office: "Mumbai HQ",
        phone: "+91-22-555-0101",
        mobile: "+91-9000000101",
        streetAddress: "1 BKC Road",
        city: "Mumbai",
        state: "MH",
        zip: "400051",
        country: "IN",
        description: "Sales rep - West region",
        memberOf: ["Domain Users", "Sales-Team"],
        enabled: true,
        locked: false,
        mustChangePassword: false,
        cantChangePassword: false,
        neverExpires: false,
        passwordLastSet: "2025-02-01T08:00:00Z",
        lastLogon: "2025-05-13T17:21:00Z",
        created: "2024-04-15T10:30:00Z",
        ouPath: "Sales",
        logonHours: "All",
        logonTo: "All computers",
        profilePath: "",
        loginScript: "",
        homeDir: "",
        homeDrive: "",
      },
      {
        sAMAccountName: "ksmith",
        upn: "ksmith@corp.cloudlab.local",
        name: "ksmith",
        givenName: "Karen",
        surname: "Smith",
        initials: "K.S.",
        displayName: "Karen Smith",
        email: "ksmith@corp.cloudlab.local",
        department: "Sales",
        title: "Sales Director",
        manager: "",
        office: "Mumbai HQ",
        phone: "+91-22-555-0102",
        mobile: "+91-9000000102",
        streetAddress: "1 BKC Road",
        city: "Mumbai",
        state: "MH",
        zip: "400051",
        country: "IN",
        description: "Director of Sales",
        memberOf: ["Domain Users", "Sales-Team", "Domain Admins"],
        enabled: true,
        locked: false,
        mustChangePassword: false,
        cantChangePassword: false,
        neverExpires: false,
        passwordLastSet: "2025-01-20T08:00:00Z",
        lastLogon: "2025-05-14T08:55:00Z",
        created: "2024-02-01T09:00:00Z",
        ouPath: "Sales",
        logonHours: "All",
        logonTo: "All computers",
        profilePath: "",
        loginScript: "",
        homeDir: "",
        homeDrive: "",
      },
      {
        sAMAccountName: "msingh",
        upn: "msingh@corp.cloudlab.local",
        name: "msingh",
        givenName: "Mira",
        surname: "Singh",
        initials: "M.S.",
        displayName: "Mira Singh",
        email: "msingh@corp.cloudlab.local",
        department: "Marketing",
        title: "Marketing Manager",
        manager: "",
        office: "Bengaluru",
        phone: "+91-80-555-0201",
        mobile: "+91-9000000201",
        streetAddress: "100 MG Road",
        city: "Bengaluru",
        state: "KA",
        zip: "560001",
        country: "IN",
        description: "Manages marketing campaigns",
        memberOf: ["Domain Users", "Marketing-Team"],
        enabled: true,
        locked: false,
        mustChangePassword: false,
        cantChangePassword: false,
        neverExpires: false,
        passwordLastSet: "2025-03-05T08:00:00Z",
        lastLogon: "2025-05-14T09:10:00Z",
        created: "2024-06-12T11:00:00Z",
        ouPath: "Marketing",
        logonHours: "All",
        logonTo: "All computers",
        profilePath: "",
        loginScript: "",
        homeDir: "",
        homeDrive: "",
      },
      {
        sAMAccountName: "asharma",
        upn: "asharma@corp.cloudlab.local",
        name: "asharma",
        givenName: "Ankit",
        surname: "Sharma",
        initials: "A.S.",
        displayName: "Ankit Sharma",
        email: "asharma@corp.cloudlab.local",
        department: "IT",
        title: "Systems Administrator",
        manager: "",
        office: "Delhi DC",
        phone: "+91-11-555-0001",
        mobile: "+91-9000000001",
        streetAddress: "Connaught Place",
        city: "New Delhi",
        state: "DL",
        zip: "110001",
        country: "IN",
        description: "Lead infrastructure engineer",
        memberOf: ["Domain Users", "IT-Admins", "Domain Admins", "Group Policy Creator Owners"],
        enabled: true,
        locked: false,
        mustChangePassword: false,
        cantChangePassword: false,
        neverExpires: true,
        passwordLastSet: "2025-04-01T08:00:00Z",
        lastLogon: "2025-05-14T07:00:00Z",
        created: "2024-01-12T09:00:00Z",
        ouPath: "IT",
        logonHours: "All",
        logonTo: "All computers",
        profilePath: "",
        loginScript: "",
        homeDir: "",
        homeDrive: "",
      },
    ],
    groups: [
      { name: "Domain Admins", scope: "Global", category: "Security", description: "Designated administrators of the domain", members: ["admin", "ksmith", "asharma"], builtin: true, ouPath: "Users" },
      { name: "Enterprise Admins", scope: "Universal", category: "Security", description: "Designated administrators of the enterprise", members: ["admin"], builtin: true, ouPath: "Users" },
      { name: "Schema Admins", scope: "Universal", category: "Security", description: "Designated administrators of the schema", members: ["admin"], builtin: true, ouPath: "Users" },
      { name: "Domain Users", scope: "Global", category: "Security", description: "All domain users", members: ["admin", "jdoe", "ksmith", "msingh", "asharma"], builtin: true, ouPath: "Users" },
      { name: "Domain Computers", scope: "Global", category: "Security", description: "All workstations and servers joined to the domain", members: [], builtin: true, ouPath: "Users" },
      { name: "Group Policy Creator Owners", scope: "Global", category: "Security", description: "Members in this group can modify group policy for the domain", members: ["admin", "asharma"], builtin: true, ouPath: "Users" },
      { name: "IT-Admins", scope: "Global", category: "Security", description: "Internal IT operations team", members: ["asharma"], builtin: false, ouPath: "IT" },
      { name: "Sales-Team", scope: "Global", category: "Security", description: "All Sales department members", members: ["jdoe", "ksmith"], builtin: false, ouPath: "Sales" },
      { name: "Marketing-Team", scope: "Global", category: "Security", description: "All Marketing department members", members: ["msingh"], builtin: false, ouPath: "Marketing" },
    ],
    computers: [
      { name: "DC01", dnsName: "DC01.corp.cloudlab.local", os: "Windows Server 2022 Datacenter", osVersion: "10.0 (20348)", enabled: true, description: "Primary domain controller", ouPath: "Domain Controllers", lastLogon: "2025-05-14T07:00:00Z", servicePack: "" },
      { name: "DC02", dnsName: "DC02.corp.cloudlab.local", os: "Windows Server 2022 Datacenter", osVersion: "10.0 (20348)", enabled: true, description: "Secondary domain controller", ouPath: "Domain Controllers", lastLogon: "2025-05-14T07:00:00Z", servicePack: "" },
      { name: "WK-001", dnsName: "WK-001.corp.cloudlab.local", os: "Windows 11 Enterprise", osVersion: "10.0 (22631)", enabled: true, description: "Sales workstation", ouPath: "_Computers", lastLogon: "2025-05-14T09:00:00Z", servicePack: "" },
      { name: "WK-002", dnsName: "WK-002.corp.cloudlab.local", os: "Windows 11 Enterprise", osVersion: "10.0 (22631)", enabled: true, description: "Marketing workstation", ouPath: "_Computers", lastLogon: "2025-05-13T18:30:00Z", servicePack: "" },
      { name: "WK-003", dnsName: "WK-003.corp.cloudlab.local", os: "Windows 10 Enterprise", osVersion: "10.0 (19045)", enabled: true, description: "Finance workstation", ouPath: "_Computers", lastLogon: "2025-05-14T08:45:00Z", servicePack: "" },
      { name: "LAPTOP-001", dnsName: "LAPTOP-001.corp.cloudlab.local", os: "Windows 11 Pro", osVersion: "10.0 (22631)", enabled: true, description: "IT laptop", ouPath: "_Computers", lastLogon: "2025-05-14T07:05:00Z", servicePack: "" },
      { name: "SRV-FILE-01", dnsName: "SRV-FILE-01.corp.cloudlab.local", os: "Windows Server 2022 Standard", osVersion: "10.0 (20348)", enabled: true, description: "File server", ouPath: "Computers", lastLogon: "2025-05-14T07:00:00Z", servicePack: "" },
    ],
    gpos: [
      {
        id: "{31B2F340-016D-11D2-945F-00C04FB984F9}",
        name: "Default Domain Policy",
        description: "Built-in default domain policy",
        builtin: true,
        links: [{ ou: "", enforced: false, enabled: true }],
        securityFiltering: ["Authenticated Users"],
        wmiFilter: "",
        created: "2024-01-10T08:00:00Z",
        modified: "2024-01-10T08:00:00Z",
        version: { user: 0, computer: 4 },
        settings: {
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Maximum password age": "42 days",
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Minimum password length": "7 characters",
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Password must meet complexity requirements": "Enabled",
          "Computer/Windows Settings/Security Settings/Account Policies/Account Lockout Policy/Account lockout threshold": "5 invalid attempts",
        },
      },
      {
        id: "{6AC1786C-016F-11D2-945F-00C04FB984F9}",
        name: "Default Domain Controllers Policy",
        description: "Built-in policy for Domain Controllers OU",
        builtin: true,
        links: [{ ou: "Domain Controllers", enforced: false, enabled: true }],
        securityFiltering: ["Authenticated Users"],
        wmiFilter: "",
        created: "2024-01-10T08:00:00Z",
        modified: "2024-01-10T08:00:00Z",
        version: { user: 0, computer: 2 },
        settings: {
          "Computer/Windows Settings/Security Settings/Local Policies/Audit Policy/Audit account logon events": "Success, Failure",
          "Computer/Windows Settings/Security Settings/Local Policies/Audit Policy/Audit logon events": "Success, Failure",
        },
      },
      {
        id: "{A1B2C3D4-1111-2222-3333-444455556666}",
        name: "Password Policy",
        description: "Fine-grained password policy supplement",
        builtin: false,
        links: [{ ou: "", enforced: true, enabled: true }],
        securityFiltering: ["Authenticated Users"],
        wmiFilter: "",
        created: "2024-03-12T09:00:00Z",
        modified: "2025-01-15T14:22:00Z",
        version: { user: 0, computer: 6 },
        settings: {
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Minimum password length": "12 characters",
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Maximum password age": "90 days",
          "Computer/Windows Settings/Security Settings/Account Policies/Password Policy/Enforce password history": "24 passwords remembered",
        },
      },
      {
        id: "{B1B2C3D4-2222-3333-4444-555566667777}",
        name: "Workstation Lockdown",
        description: "Locks down standard workstations",
        builtin: false,
        links: [{ ou: "_Computers", enforced: false, enabled: true }],
        securityFiltering: ["Authenticated Users"],
        wmiFilter: "",
        created: "2024-05-20T11:00:00Z",
        modified: "2025-02-10T16:00:00Z",
        version: { user: 4, computer: 12 },
        settings: {
          "User/Administrative Templates/System/Prevent access to the command prompt": "Enabled",
          "User/Administrative Templates/Start Menu and Taskbar/Remove Run menu from Start Menu": "Enabled",
          "Computer/Administrative Templates/System/Removable Storage Access/All Removable Storage classes: Deny all access": "Enabled",
        },
      },
      {
        id: "{C1B2C3D4-3333-4444-5555-666677778888}",
        name: "RDP Restriction",
        description: "Restricts RDP to IT-Admins only",
        builtin: false,
        links: [{ ou: "IT", enforced: false, enabled: true }],
        securityFiltering: ["IT-Admins"],
        wmiFilter: "",
        created: "2024-08-01T10:00:00Z",
        modified: "2025-03-01T12:00:00Z",
        version: { user: 0, computer: 8 },
        settings: {
          "Computer/Administrative Templates/Windows Components/Remote Desktop Services/Remote Desktop Session Host/Connections/Allow users to connect remotely by using Remote Desktop Services": "Enabled",
        },
      },
    ],
    dnsZones: [
      {
        name: "corp.cloudlab.local",
        type: "Primary",
        direction: "Forward",
        adIntegrated: true,
        replicationScope: "To all DNS servers running on domain controllers in this domain",
        dynamicUpdates: "Secure only",
        records: [
          { name: "@", type: "SOA", data: "dc01.corp.cloudlab.local. hostmaster.corp.cloudlab.local. (1 900 600 86400 3600)", timestamp: "static" },
          { name: "@", type: "NS", data: "dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "@", type: "NS", data: "dc02.corp.cloudlab.local.", timestamp: "static" },
          { name: "@", type: "A", data: "192.168.1.10", timestamp: "2025-05-14T07:00:00Z" },
          { name: "@", type: "A", data: "192.168.1.11", timestamp: "2025-05-14T07:00:00Z" },
          { name: "dc01", type: "A", data: "192.168.1.10", timestamp: "static" },
          { name: "dc02", type: "A", data: "192.168.1.11", timestamp: "static" },
          { name: "srv-file-01", type: "A", data: "192.168.1.20", timestamp: "static" },
          { name: "wk-001", type: "A", data: "192.168.1.51", timestamp: "2025-05-14T09:00:00Z" },
          { name: "wk-002", type: "A", data: "192.168.1.52", timestamp: "2025-05-13T18:30:00Z" },
          { name: "fileserver", type: "CNAME", data: "srv-file-01.corp.cloudlab.local.", timestamp: "static" },
          { name: "mail", type: "MX", data: "10 mail01.corp.cloudlab.local.", timestamp: "static" },
          { name: "@", type: "TXT", data: '"v=spf1 mx -all"', timestamp: "static" },
        ],
      },
      {
        name: "_msdcs.corp.cloudlab.local",
        type: "Primary",
        direction: "Forward",
        adIntegrated: true,
        replicationScope: "To all DNS servers running on domain controllers in this forest",
        dynamicUpdates: "Secure only",
        records: [
          { name: "@", type: "SOA", data: "dc01.corp.cloudlab.local. hostmaster.corp.cloudlab.local. (1 900 600 86400 3600)", timestamp: "static" },
          { name: "@", type: "NS", data: "dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "_ldap._tcp.dc", type: "SRV", data: "0 100 389 dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "_ldap._tcp.dc", type: "SRV", data: "0 100 389 dc02.corp.cloudlab.local.", timestamp: "static" },
          { name: "_kerberos._tcp.dc", type: "SRV", data: "0 100 88 dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "_kerberos._tcp.dc", type: "SRV", data: "0 100 88 dc02.corp.cloudlab.local.", timestamp: "static" },
          { name: "_ldap._tcp.gc", type: "SRV", data: "0 100 3268 dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "gc", type: "A", data: "192.168.1.10", timestamp: "static" },
        ],
      },
      {
        name: "1.168.192.in-addr.arpa",
        type: "Primary",
        direction: "Reverse",
        adIntegrated: true,
        replicationScope: "To all DNS servers running on domain controllers in this domain",
        dynamicUpdates: "Secure only",
        records: [
          { name: "@", type: "SOA", data: "dc01.corp.cloudlab.local. hostmaster.corp.cloudlab.local. (1 900 600 86400 3600)", timestamp: "static" },
          { name: "@", type: "NS", data: "dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "10", type: "PTR", data: "dc01.corp.cloudlab.local.", timestamp: "static" },
          { name: "11", type: "PTR", data: "dc02.corp.cloudlab.local.", timestamp: "static" },
          { name: "20", type: "PTR", data: "srv-file-01.corp.cloudlab.local.", timestamp: "static" },
          { name: "51", type: "PTR", data: "wk-001.corp.cloudlab.local.", timestamp: "2025-05-14T09:00:00Z" },
          { name: "52", type: "PTR", data: "wk-002.corp.cloudlab.local.", timestamp: "2025-05-13T18:30:00Z" },
        ],
      },
    ],
    activity: [],
    gpoBackups: [],
    wmiFilters: [
      { name: "Windows 11 only", description: "Applies only to Windows 11 clients", query: 'SELECT * FROM Win32_OperatingSystem WHERE Version LIKE "10.0.22%"' },
      { name: "Laptops only", description: "Applies only to devices with a battery (laptops)", query: "SELECT * FROM Win32_Battery WHERE BatteryStatus IS NOT NULL" },
      { name: "64-bit OS only", description: "Applies only to 64-bit operating systems", query: 'SELECT * FROM Win32_OperatingSystem WHERE OSArchitecture = "64-bit"' },
    ],
    recycleBin: [
      { id: "rb-1", kind: "User", name: "tmpuser01", deletedOn: "2025-04-02T10:00:00Z", deletedFrom: "_Disabled", lastKnownParent: "_Disabled", restored: false },
      { id: "rb-2", kind: "Computer", name: "OLD-LAPTOP-09", deletedOn: "2025-03-18T14:20:00Z", deletedFrom: "_Computers", lastKnownParent: "_Computers", restored: false },
      { id: "rb-3", kind: "Group", name: "Legacy-VPN-Users", deletedOn: "2025-02-27T09:12:00Z", deletedFrom: "IT", lastKnownParent: "IT", restored: false },
      { id: "rb-4", kind: "User", name: "contractor-temp", deletedOn: "2025-01-11T16:45:00Z", deletedFrom: "_Users", lastKnownParent: "_Users", restored: false },
      { id: "rb-5", kind: "OU", name: "Decommissioned", deletedOn: "2024-12-05T08:30:00Z", deletedFrom: "root", lastKnownParent: "root", restored: false },
    ],
    recycleBinEnabled: false,
    psos: [
      { name: "Admin-Strict-PSO", precedence: 10, minPasswordLength: 16, maxPasswordAge: 60, lockoutThreshold: 3, appliesTo: ["Domain Admins"] },
      { name: "ServiceAccount-PSO", precedence: 20, minPasswordLength: 24, maxPasswordAge: 0, lockoutThreshold: 0, appliesTo: ["_ServiceAccounts"] },
    ],
    siteLinks: [{ name: "DEFAULTIPSITELINK", transport: "IP", cost: 100, interval: 180, schedule: "24x7", sitesContained: ["Default-First-Site-Name"] }],
    subnetObjects: [{ prefix: "192.168.1.0/24", site: "Default-First-Site-Name", location: "HQ", description: "Primary LAN" }],
    connectionObjects: [
      { id: "co-1", name: "DC01 <- DC02", owner: "DC01", replicateFrom: "DC02", transport: "IP", schedule: "Every 15 minutes", enabled: true, auto: true },
      { id: "co-2", name: "DC02 <- DC01", owner: "DC02", replicateFrom: "DC01", transport: "IP", schedule: "Every 15 minutes", enabled: true, auto: true },
    ],
    dcState: {
      DC01: { usn: 48213, lastSync: "2025-05-14T07:00:00Z" },
      DC02: { usn: 48197, lastSync: "2025-05-14T06:55:00Z" },
    },
    replicationEvents: [
      { time: "2025-05-14T07:00:00Z", source: "DC01", dest: "DC02", message: "Replication completed successfully", level: "Information" },
      { time: "2025-05-14T06:55:00Z", source: "DC02", dest: "DC01", message: "Replication completed successfully", level: "Information" },
      { time: "2025-05-13T22:10:00Z", source: "DC01", dest: "DC02", message: "Replication latency above threshold (12 min)", level: "Warning" },
    ],
    aadConnect: {
      syncIntervalMin: 30,
      lastRun: "2025-05-14T07:00:00Z",
      nextRun: "2025-05-14T07:30:00Z",
      stagingMode: false,
      syncedObjects: 512,
      pendingExports: 0,
      connectors: [
        { name: "corp.cloudlab.local", kind: "AD", objectCount: 512, lastFullImport: "2025-05-01T02:00:00Z", lastDeltaSync: "2025-05-14T07:00:00Z" },
        { name: "cloudlab.onmicrosoft.com - Entra ID", kind: "EntraID", objectCount: 512, lastFullImport: "2025-05-01T02:05:00Z", lastDeltaSync: "2025-05-14T07:00:00Z" },
      ],
    },
    bitlocker: [
      { deviceName: "LAPTOP-001", driveLabel: "C:", recoveryKeyId: "4F2A9B10", recoveryKey: "123456-234567-345678-456789-567890-678901-789012-890123", lastBackup: "2025-04-20T08:00:00Z" },
      { deviceName: "WK-001", driveLabel: "C:", recoveryKeyId: "9C3D1E22", recoveryKey: "111111-222222-333333-444444-555555-666666-777777-888888", lastBackup: "2025-03-15T09:00:00Z" },
    ],
    tools: {
      laps: {
        enabled: true,
        passwordAgeDays: 30,
        retrievals: [{ device: "WK-002", retrievedBy: "asharma", time: "2025-05-10T11:00:00Z" }],
      },
      adcs: {
        caName: "CORP-DC01-CA",
        templates: [
          { name: "Computer", enrolleeSuppliesSubject: false, validityYears: 1 },
          { name: "User", enrolleeSuppliesSubject: false, validityYears: 1 },
          { name: "Web Server", enrolleeSuppliesSubject: true, validityYears: 2 },
        ],
        issued: [
          { template: "Computer", subject: "DC01.corp.cloudlab.local", issued: "2024-01-10T08:00:00Z", expires: "2025-01-10T08:00:00Z" },
          { template: "Web Server", subject: "portal.corp.cloudlab.local", issued: "2024-11-01T08:00:00Z", expires: "2026-11-01T08:00:00Z" },
        ],
      },
      dfsn: { namespaces: [{ name: "\\\\corp.cloudlab.local\\public", type: "Domain-based", targets: ["\\\\SRV-FILE-01\\public"] }] },
      trusts: {
        forestFunctionalLevel: "Windows Server 2022",
        upnSuffixes: ["corp.cloudlab.local"],
        relationships: [],
      },
      adsi: { lastBrowsedContext: "Default naming context" },
      adfs: { federationServiceName: "sts.corp.cloudlab.local", relyingParties: [{ name: "Microsoft Office 365 Identity Platform", identifier: "urn:federation:MicrosoftOnline", enabled: true }] },
      kerberos: {
        spns: [
          { account: "DC01", spn: "HOST/dc01.corp.cloudlab.local" },
          { account: "SRV-FILE-01", spn: "CIFS/srv-file-01.corp.cloudlab.local" },
        ],
        delegation: [{ account: "SRV-FILE-01", type: "Constrained", services: ["CIFS/srv-file-01.corp.cloudlab.local"] }],
      },
      dhcp: {
        scopes: [{ name: "HQ-Scope", subnet: "192.168.1.0/24", startRange: "192.168.1.100", endRange: "192.168.1.200", leaseDurationHours: 8, leasesUsed: 42, leasesTotal: 100 }],
      },
      services: [
        { name: "Active Directory Domain Services", status: "Running", startupType: "Automatic" },
        { name: "DNS Server", status: "Running", startupType: "Automatic" },
        { name: "DFS Replication", status: "Running", startupType: "Automatic" },
        { name: "Print Spooler", status: "Stopped", startupType: "Manual" },
      ],
      taskScheduler: [
        { name: "\\Microsoft\\Windows\\Active Directory Rights Management Services Client\\AD RMS Rights Policy Template Management (Automated)", status: "Ready", lastRun: "2025-05-14T06:00:00Z", nextRun: "2025-05-15T06:00:00Z", trigger: "Daily 06:00" },
      ],
      firewall: [
        { name: "AD DS - Domain Controller (LDAP-TCP-In)", direction: "Inbound", action: "Allow", enabled: true, profile: "Domain" },
        { name: "AD DS - Domain Controller (RPC-In)", direction: "Inbound", action: "Allow", enabled: true, profile: "Domain" },
      ],
      nps: {
        clients: [{ name: "WiFi-Controller-01", ip: "192.168.1.5", sharedSecretSet: true, vendor: "RADIUS Standard" }],
        policies: [{ name: "Corporate Wi-Fi Access", type: "Network Policy", enabled: true, conditions: "Windows Groups: Domain Users", processingOrder: 1 }],
      },
      rras: {
        vpnServers: [{ name: "DC01", type: "SSTP/IKEv2", status: "Running" }],
        routingInterfaces: [{ name: "Local Area Connection", type: "Ethernet", status: "Enabled" }],
      },
    },
  };
}
